In [6]:
!pip install tabula-py

Collecting tabula-py
  Using cached tabula_py-2.5.1-py3-none-any.whl (12.0 MB)
Collecting pandas>=0.25.3
  Using cached pandas-1.4.3-cp310-cp310-win_amd64.whl (10.5 MB)
Requirement already satisfied: distro in c:\python310\lib\site-packages (from tabula-py) (1.7.0)
Requirement already satisfied: numpy in c:\python310\lib\site-packages (from tabula-py) (1.23.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\admin\appdata\roaming\python\python310\site-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\python310\lib\site-packages (from pandas>=0.25.3->tabula-py) (2022.2.1)
Requirement already satisfied: six>=1.5 in c:\python310\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.25.3->tabula-py) (1.16.0)
Installing collected packages: pandas, tabula-py
Successfully installed pandas-1.4.3 tabula-py-2.5.1

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)

In [7]:
import tabula

In [8]:
from tabula.io import read_pdf

In [9]:
import pandas as pd

In [10]:
!pip install pandas xlrd==2.0.1

Requirement already satisfied: pandas in c:\python310\lib\site-packages (1.4.3)
Collecting xlrd==2.0.1
  Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\admin\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in c:\python310\lib\site-packages (from pandas) (1.23.1)
Requirement already satisfied: pytz>=2020.1 in c:\python310\lib\site-packages (from pandas) (2022.2.1)
Requirement already satisfied: six>=1.5 in c:\python310\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: xlrd

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Python310\\Scripts\\runxlrd.py'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)

In [15]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     -------------------------------------- 242.1/242.1 kB 3.7 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)

In [11]:
def data_extract(url):
    df = read_pdf(url,pages="all")
    for i in range(1, len(df)):
        df[0] = pd.concat([df[0],df[i]], axis=0)
    return df[0]

In [12]:
data_extract('https://kptclsldc.in/Transmission Outage/2018/DEC-18/04to10DEC2018.pdf')

,Sl.No,Date,Tr_ZONE,Voltage,Line,Station_Name,Open_At,Closed_At,Duration,REASON
0,1,4-Dec-18,BAGALKOT,220,"220/110KV,HV1","ATHANI_220,HALIYAL\rLIS_110,KSSKN_110,SATTI_11...",5:58,7:05,1:07,TRANSFORMER FAULT
1,2,4-Dec-18,BAGALKOT,220,"220/110KV,HV2,LV2",ATHANI_220,10:18,17:00,6:42,TRANSFORMER FAULT
2,3,4-Dec-18,BAGALKOT,110,"110/11KV,HV2",BELUR_110,5:30,5:57,0:27,TRANSFORMER FAULT
3,4,4-Dec-18,BAGALKOT,110,"110/11KV,HV2",BELUR_110,13:40,14:38,0:58,HAND TRIPPED
4,5,4-Dec-18,BAGALKOT,220,BELGAUM2-CHIKKODI,CHIKKOD_220,15:56,15:58,0:02,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
23,754,10-Dec-18,TUMKUR,66,HONNALLI 220KV- SASUVEHALLI,SASUVEHALLI_66,1:11,1:22,0:10,LINE FAULT
24,755,10-Dec-18,TUMKUR,66,TR-1,KORA_66,2:03,4:29,2:25,TRANSFORMER FAULT
25,756,10-Dec-18,TUMKUR,66,TR-1,KORATAGERE_66,12:39,12:48,0:09,TRANSFORMER FAULT
26,757,10-Dec-18,TUMKUR,66,KUKKAWADA- LINGADAHALLI,"TYAVANAGI_66, BASAVAPATNA_66,\rSANTEBENNUR_66",22:24,22:31,0:07,LINE FAULT
0,758,10-Dec-18,TUMKUR,66,TR-2,THOVINAKERE_66,11:40,13:03,1:22,TRANSFORMER FAULT

In [16]:
def data_extract1(url, header):
    df = pd.read_excel(url, header=[header])
    return df

In [82]:
data_extract1('https://kptclsldc.in/Transmission%20Outage/2019/APR-2019/02APR2019to08APR2019.xlsx', 2)

,Sl.No.,DATE,Tr_ZONE,Voltage,Line,Unnamed: 5,Station_Name,Unnamed: 7,Open_At,Closed_At,Duration,REASON,Unnamed: 12
0,1,2019-04-02,BAGALKOT,110,NaN,"110/11KV,HV-1",NaN,ANAND NAGAR_110,10:30:00,16:38:00,06:08:00,NaN,LINE CLEAR AVAILED
1,2,2019-04-02,BAGALKOT,110,NaN,HUNAGUND -B.BAGEWADI(KUDALASANGAM),NaN,KUDALASANGAM_110,10:33:00,10:38:00,00:05:00,NaN,LOAD CHANGEOVER
2,3,2019-04-02,BAGALKOT,110,NaN,KADANAKOPPA-KAVALAWAD,NaN,KAVALAWAD_110,06:46:00,07:29:00,00:43:00,NaN,LINE FAULT
3,4,2019-04-02,BAGALKOT,220,NaN,BIDNAL-NARENDRA,NaN,BIDNAL_220,11:14:00,14:46:00,03:32:00,NaN,NFBC ISSUED
4,5,2019-04-02,BAGALKOT,220,NaN,BIDNAL-HARTI 2,NaN,BIDNAL_220,07:42:00,13:39:00,05:57:00,NaN,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,708,2019-04-08,TUMKUR,66,NaN,BADDIHALLI- MELEKOTE,NaN,BADDIHALLI_66,12:52:25,15:19:14,02:26:49,NaN,LINE CLEAR AVAILED
708,709,2019-04-08,TUMKUR,66,NaN,HIREHALLI - MELEKOTE,NaN,HIREHALLY_66,15:07:29,15:14:31,00:07:02,NaN,LINE FAULT
709,710,2019-04-08,TUMKUR,66,NaN,TR-1( LV1),NaN,HONNALLI_220,13:00:35,13:12:48,00:12:13,NaN,HAND TRIPPED
710,711,2019-04-08,TUMKUR,66,NaN,HONNALLI 220kV- CHANNAGIRI,NaN,"CHANNAGIRI_66, DEVARAHALLI_66, BENKIKERE_66, T...",12:57:43,13:11:17,00:13:34,NaN,HAND TRIPPED
711,712,2019-04-08,TUMKUR,66,NaN,HONNALLI 220KV- SASUVEHALLI,NaN,SASUVEHALLI_66,12:57:41,13:12:48,00:15:07,NaN,HAND TRIPPED

In [145]:
import os

print(os.getcwd())

C:\C-STEP FOLDER

In [146]:
pdf_files = [os.path.join(root, name)
             for root, dirs, files in os.walk(os.getcwd())
             for name in files
             if name.endswith((".pdf"))]

In [147]:
def data_pdf(file):
    df = read_pdf(file, pages='all')
    list1 = [] 
    for item in df:
        for info in item.values:
            list1.append(info)
    df = pd.DataFrame(list1)
    return df

In [148]:
from IPython.display import display

In [149]:

for f in pdf_files:
    print(f)
    display(data_pdf(f))

C:\C-STEP FOLDER\Transmission outage\2018\INTERRUPTIONS_01octTO08oct2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,1-Oct-18,Bagalkot,220,- XELDOM-AMBEWADI,AMBEWADI_220,12:00,20:15,8:15,LINE CLEAR AVAILED
1,2,1-Oct-18,Bagalkot,220,A NARENDRA 2 - AMBEWADI,AMBEWADI_220,14:39,17:45,3:06,HAND TRIPPED
2,3,1-Oct-18,Bagalkot,110,B ANKALAGI - HIDIKAL,HIDIKAL_110,8:47,18:25,9:38,LINE CLEAR AVAILED
3,4,1-Oct-18,Bagalkot,110,"E 110/11KV, HV2",BAGALKOT_110,8:34,8:42,0:08,ON TRANSFORMER FAULT
4,5,1-Oct-18,Bagalkot,110,"W 110/33KV, HV3",HIDIKAL_110,20:46,21:18,0:32,ON TRANSFORMER FAULT
...,...,...,...,...,...,...,...,...,...,...
1279,1314,8-Oct-18,Tumkur,110,TR-1 & TR-2,KBCROSS_220,12:57,16:59,4:02,HAND TRIPPED
1280,1315,8-Oct-18,Tumkur,110,KB CROSS 220kV- MAYASANDRA,"MAYASANDRA_110, TANDAGA_110,\rKADEHALLI_110",12:11,17:06,4:55,HAND TRIPPED
1281,1316,8-Oct-18,Tumkur,220,TR-1 & TR-2(HV SIDE ),KBCROSS_220,14:58,16:58,2:00,HAND TRIPPED
1282,1317,8-Oct-18,Tumkur,220,KB CROSS 220kV- NELAMANGALA,KBCROSS_220,9:10,19:32,10:21,LINE CLEAR AVILED
1283,1318,8-Oct-18,Tumkur,220,KB CROSS 220kV- SHIMOGA,MRSMG_220,12:01,16:38,4:37,ON LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2018\DEC 2018\04to10DEC2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,4-Dec-18,BAGALKOT,220,"220/110KV,HV1","ATHANI_220,HALIYAL\rLIS_110,KSSKN_110,SATTI_11...",5:58,7:05,1:07,TRANSFORMER FAULT
1,2,4-Dec-18,BAGALKOT,220,"220/110KV,HV2,LV2",ATHANI_220,10:18,17:00,6:42,TRANSFORMER FAULT
2,3,4-Dec-18,BAGALKOT,110,"110/11KV,HV2",BELUR_110,5:30,5:57,0:27,TRANSFORMER FAULT
3,4,4-Dec-18,BAGALKOT,110,"110/11KV,HV2",BELUR_110,13:40,14:38,0:58,HAND TRIPPED
4,5,4-Dec-18,BAGALKOT,220,BELGAUM2-CHIKKODI,CHIKKOD_220,15:56,15:58,0:02,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
753,754,10-Dec-18,TUMKUR,66,HONNALLI 220KV- SASUVEHALLI,SASUVEHALLI_66,1:11,1:22,0:10,LINE FAULT
754,755,10-Dec-18,TUMKUR,66,TR-1,KORA_66,2:03,4:29,2:25,TRANSFORMER FAULT
755,756,10-Dec-18,TUMKUR,66,TR-1,KORATAGERE_66,12:39,12:48,0:09,TRANSFORMER FAULT
756,757,10-Dec-18,TUMKUR,66,KUKKAWADA- LINGADAHALLI,"TYAVANAGI_66, BASAVAPATNA_66,\rSANTEBENNUR_66",22:24,22:31,0:07,LINE FAULT
757,758,10-Dec-18,TUMKUR,66,TR-2,THOVINAKERE_66,11:40,13:03,1:22,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2018\DEC 2018\11to17DEC2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,11-Dec-18,BAGALKOT,220,PONDA1 -AMBEWADI,AMBEWADI_220,11:30,12:12,0:42,LINE FAULT
1,2,11-Dec-18,BAGALKOT,110,SUPA2-AMBEWADI,AMBEWADI_220,9:54,12:51,2:57,HAND TRIPPED
2,3,11-Dec-18,BAGALKOT,110,SUPA1-AMBEWADI,AMBEWADI_220,12:53,15:49,2:56,HAND TRIPPED
3,4,11-Dec-18,BAGALKOT,110,"110/11KV,HV-2",ANKALI_110,12:25,12:59,0:34,HAND TRIPPED
4,5,11-Dec-18,BAGALKOT,110,"110/33KV,HV-3",KIADB BIJAPUR_110,16:37,18:12,1:35,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
729,753,17-Dec-18,TUMKUR,66,TR-1,HANGLA_66,15:02,15:08,0:05,TRANSFORMER FAULT
730,754,17-Dec-18,TUMKUR,66,HOLALKERE- RAMGIRI 2,HOLALKERE_66,9:15,9:25,0:10,HAND TRIPPED
731,755,17-Dec-18,TUMKUR,66,HOLALKERE- RAMGIRI 2,HOLALKERE_66,18:35,18:55,0:19,HAND TRIPPED
732,756,17-Dec-18,TUMKUR,66,HONNALLI 220KV- SASUVEHALLI,SASUVEHALLI_66,0:45,0:58,0:12,LINE FAULT
733,757,17-Dec-18,TUMKUR,66,HONNALLI 220kV- BANUVALLI,"BANUVALLI_66, NANDIGUDI_66,\rKARGIL_EHT_66",8:55,9:06,0:10,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2018\DEC 2018\18to24DEC2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,18-Dec-18,BAGALKOT,110,"110/11KV,HV2",BHUTHNAL_110,16:28,16:31,0:03,TRANSFORMER FAULT
1,2,18-Dec-18,BAGALKOT,110,"110/11KV,HV1",DAMBAL_110,15:18,17:00,1:42,LINE CLEAR AVAILED
2,3,18-Dec-18,BAGALKOT,110,DAVALESHWARA-SAIDAPUR,SAIDAPUR_110,8:29,12:13,3:44,HAND TRIPPED
3,4,18-Dec-18,BAGALKOT,110,"110/11KV,HV1",SAIDAPUR_110,8:31,12:13,3:42,HAND TRIPPED
4,5,18-Dec-18,BAGALKOT,110,GAMESHA-KULIGOD,KULIGOD_110,10:57,12:04,1:07,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
904,905,24-Dec-18,TUMKUR,66,TR-2,SANIKERE_66,19:33,19:54,0:21,TRANSFORMER FAULT
905,906,24-Dec-18,TUMKUR,66,SIRA- BUKKAPATNA,BUKKAPATNA_66,23:22,23:36,0:13,HAND TRIPPED
906,907,24-Dec-18,TUMKUR,66,SIRA- KALLAMBELLA,KALLAMBELLA_66,2:52,3:01,0:08,LINE FAULT
907,908,24-Dec-18,TUMKUR,66,SIRA- MADHUGIRI 2,"BUKKAPATNA_66, KALLAMBELLA_66",2:52,3:01,0:08,LINE FAULT
908,909,24-Dec-18,TUMKUR,66,SAVALANGA 66kV-HNLI220_NYMT,SAVALANGA_66,13:15,14:23,1:08,MAIN SUPPLY FAILURE

C:\C-STEP FOLDER\Transmission outage\2018\DEC 2018\25to31DEC2018.pdf

,0,1,2,3,4,5,6,7,8,9,10
0,1.0,24-Dec-18,BAGALKOT,220.0,NAGJHARI 1-AMBEWADI,AMBEWADI_220,9:31,17:06,7:35,LINE CLEAR AVAILED,None
1,2.0,24-Dec-18,BAGALKOT,220.0,PONDA 2 -AMBEWADI,AMBEWADI_220,0:00,15:56,15:56,LINE CLEAR AVAILED,None
2,3.0,24-Dec-18,BAGALKOT,220.0,PONDA 2 -AMBEWADI,AMBEWADI_220,22:07,23:59,1:52,LINE FAULT,None
3,4.0,24-Dec-18,BAGALKOT,220.0,CHIKKODI 220-BELGAUM 1,CHIKKODI_220,0:00,9:27,9:27,LINE CLEAR AVAILED,None
4,5.0,24-Dec-18,BAGALKOT,110.0,"110/11KV,HV-1",BIDNAL_220,11:15,16:47,5:32,HAND TRIPPED,None
...,...,...,...,...,...,...,...,...,...,...,...
801,778.0,31-Dec-18,TUMKUR,66.0,SIRA- KALLAMBELLA,KALLAMBELLA_66,8:55,9:18,0:23,LINE FAULT,None
802,779.0,31-Dec-18,TUMKUR,66.0,SIRA- MADHUGIRI 2,"BUKKAPATNA_66, KALLAMBELLA_66",8:55,9:18,0:23,LINE FAULT,None
803,780.0,31-Dec-18,TUMKUR,66.0,TR2,TAVAREKERE(C)_66,21:21,21:25,0:03,MAIN SUPPLY FAILURE,None
804,781.0,31-Dec-18,TUMKUR,66.0,UCHANGIDURGA- PALLAGATTE,"PALLAGATTE_66,SOKKE_66",14:27,15:03,0:35,LINE FAULT,None
805,782.0,31-Dec-18,TUMKUR,66.0,TR-1,YEDIYUR_66,13:16,18:12,4:56,LINE CLEAR AVAILED,None

C:\C-STEP FOLDER\Transmission outage\2018\NOV 2018\06to12NOV2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,6-Nov-18,BAGALKOT,110,"110/11KV,HV-2",BAGALKOT_110,12:12,12:22,0:10,TRANSFORMER FAULT
1,2,6-Nov-18,BAGALKOT,110,"110/11KV,HV-3",BAILHONGAL_110,19:26,22:15,2:49,TRANSFORMER FAULT
2,3,6-Nov-18,BAGALKOT,110,"110/11KV,HV-2",NIPPANI_110,10:05,10:45,0:40,TRANSFORMER FAULT
3,4,6-Nov-18,BAGALKOT,110,"110/11KV,HV-2",RANNABELAGALI_110,17:58,18:15,0:17,TRANSFORMER FAULT
4,5,6-Nov-18,BAGALKOT,110,TERADAL-SVRG,TERADAL_110,9:10,10:03,0:53,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
575,576,12-Nov-18,TUMKUR,66,TR-1 &2,HARIHAR_66,10:39,13:34,2:55,LINE CLEAR AVAILED
576,577,12-Nov-18,TUMKUR,66,TR-1,MYLANAHALLI_66,10:38,11:00,0:21,TRANSFORMER FAULT
577,578,12-Nov-18,TUMKUR,66,SAVALANGA- HONNALLI,SAVALANGA_66,9:57,17:36,7:39,LINE CLEAR AVAILED
578,579,12-Nov-18,TUMKUR,66,TR-1,SAVALANGA_66,9:57,17:37,7:40,LINE CLEAR AVAILED
579,580,12-Nov-18,TUMKUR,66,HANAGAL- AVADASOLAR_IPP_66,AVADASOLAR_IPP_66,11:12,11:30,0:17,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2018\NOV 2018\13to19NOV2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,SL NO,DATE,Tr_ZONE,Voltage,Line/Transformer,NAME OF THE STATION,Open _at,Closed_At,Duration,REASON
1,1,13-Nov-18,BAGALKOT,220,AMBEWADI-NERENDRA 2,AMBEWADI_220,10:31,11:37,1:06,LINE CLEAR AVAILED
2,2,13-Nov-18,BAGALKOT,110,CHIKKODI-SANKESHWAR,SANKESHWAR_110,16:25,16:44,0:19,LINE FAULT
3,3,13-Nov-18,BAGALKOT,110,DAMBAL-GADAG2(L4),SAMBAPUR ROAD_110,16:52,23:59,7:07,LINE FAULT
4,4,13-Nov-18,BAGALKOT,110,"110/11KV,HV-1",DAMBAL_110,19:12,19:56,0:44,MAIN SUPPLY FAILURE
...,...,...,...,...,...,...,...,...,...,...
857,857,19-Nov-18,TUMKUR,66,DYAVARANAHALLI-RANGENAHALLI (P R\rPURA),"PRPURA_66,\rLINGADAHALLI_TMK2_66",17:36,17:44,0:08,HAND TRIPPED
858,858,19-Nov-18,TUMKUR,66,GUTTUR 66kV- DAVANGERE,GUTTUR_66,9:59,11:27,1:27,LINE CLEAR AVAILED
859,859,19-Nov-18,TUMKUR,66,TR-1,HIRIYUR_66,7:21,7:32,0:11,TRANSFORMER FAULT
860,860,19-Nov-18,TUMKUR,66,HIRIYUR 220KV- RKP 1,RKP1_IPP_66,0:45,8:05,7:19,HAND TRIPPED
861,861,19-Nov-18,TUMKUR,66,HIRIYUR 220KV- RKP 2,RKP2_IPP_66,0:45,8:05,7:19,HAND TRIPPED

C:\C-STEP FOLDER\Transmission outage\2018\NOV 2018\20to26NOV2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,20-Nov-18,BAGALKOT,110,"110/11KV,HV1",DAMBAL_110,19:02,19:11,0:09,HAND TRIPPED
1,2,20-Nov-18,BAGALKOT,220,HARTI1-BIDNAL,BIDNAL_220,0:00,13:20,13:20,LINE CLEAR AVAILED
2,3,20-Nov-18,BAGALKOT,220,HARTI2-BIDNAL,BIDNAL_220,11:04,13:29,2:25,LINE CLEAR AVAILED
3,4,20-Nov-18,BAGALKOT,220,CHIKKODI2-BELGAUM,BELGAUM_220,2:03,7:04,5:01,HAND TRIPPED
4,5,20-Nov-18,BAGALKOT,220,CHIKKODI2-BELGAUM,BELGAUM_220,12:48,23:59,11:11,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
698,699,26-Nov-18,TUMKUR,66,DAVANGERE SRS- SOKKE,"MELLEKATTE_66, SOKKE_66",16:05,16:19,0:13,LINE FAULT
699,700,26-Nov-18,TUMKUR,66,TR-1,HARAPPANAHALLI_66,12:22,14:07,1:44,TRANSFORMER FAULT
700,701,26-Nov-18,TUMKUR,66,TR-2,HONNALI_66,16:55,17:05,0:10,TRANSFORMER FAULT
701,702,26-Nov-18,TUMKUR,66,HONNALLI 220kV- CHANNAGIRI,"CHANNAGIRI_66, DEVARAHALLI_66,\rBENKIKERE_66, ...",13:55,15:51,1:56,LINE FAULT
702,703,26-Nov-18,TUMKUR,66,KUKKAWADA- LINGADAHALLI,"TYAVANAGI_66, BASAVAPATNA_66,\rSANTEBENNUR_66",11:44,11:50,0:06,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2018\NOV 2018\27NOVto03DEC2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,27-Nov-18,BAGALKOT,110,BELLATTI - ENERCON 2,BELLATTI_110,11:55,13:03,1:08,LINE CLEAR AVAILED
1,2,27-Nov-18,BAGALKOT,110,GADAG ROAD -GOANAKOPPA,GADAG ROAD_110,11:28,11:32,0:04,HAND TRIPPED
2,3,27-Nov-18,BAGALKOT,110,GOPANAKOPPA-MRUTYUNJANAGR,MRUTYUNJAYANAGAR_110,11:32,12:52,1:20,HAND TRIPPED
3,4,27-Nov-18,BAGALKOT,110,GOPANAKOPPA-MRUTYUNJANAGR 2,MRUTYUNJAYANAGAR_110,11:35,12:52,1:17,HAND TRIPPED
4,5,27-Nov-18,BAGALKOT,110,GAOPANAKOPPA-GADAG ROAD,GADAG ROAD_110,12:52,12:57,0:05,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
659,660,3-Dec-18,TUMKUR,66,TR-1(HV SIDE),DAVANGERE_SRS_220,16:07,16:28,0:21,HAND TRIPPED
660,661,3-Dec-18,TUMKUR,66,DYAVARANAHALLI-RANGENAHALLI (P R\rPURA),"PRPURA_66, LINGADAHALLI_TMK2_66",8:32,17:47,9:14,HAND TRIPPED
661,662,3-Dec-18,TUMKUR,66,TR-1,HALUVAGALU_66,12:03,12:53,0:49,LINE CLEAR AVAILED
662,663,3-Dec-18,TUMKUR,66,NEELAGUNDA 220kV-HARAPPANAHALLI,HARAPPANAHALLI_66,6:17,7:21,1:03,LINE FAULT
663,664,3-Dec-18,TUMKUR,66,TR-1,HONNALI_66,11:48,12:00,0:11,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2018\OCT 2018\01to08oct2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,1-Oct-18,Bagalkot,220,XELDOM - AMBEWADI,AMBEWADI_220,12:00,20:15,8:15,LINE CLEAR AVAILED
1,2,1-Oct-18,Bagalkot,220,NARENDRA 2 - AMBEWADI,AMBEWADI_220,14:39,17:45,3:06,HAND TRIPPED
2,3,1-Oct-18,Bagalkot,110,ANKALAGI - HIDIKAL,HIDIKAL_110,8:47,18:25,9:38,LINE CLEAR AVAILED
3,4,1-Oct-18,Bagalkot,110,"110/11KV, HV2",BAGALKOT_110,8:34,8:42,0:08,ON TRANSFORMER FAULT
4,5,1-Oct-18,Bagalkot,110,"110/33KV, HV3",HIDIKAL_110,20:46,21:18,0:32,ON TRANSFORMER FAULT
...,...,...,...,...,...,...,...,...,...,...
1279,1314,8-Oct-18,Tumkur,110,TR-1 & TR-2,KBCROSS_220,12:57,16:59,4:02,HAND TRIPPED
1280,1315,8-Oct-18,Tumkur,110,KB CROSS 220kV- MAYASANDRA,"MAYASANDRA_110, TANDAGA_110,\rKADEHALLI_110",12:11,17:06,4:55,HAND TRIPPED
1281,1316,8-Oct-18,Tumkur,220,TR-1 & TR-2(HV SIDE ),KBCROSS_220,14:58,16:58,2:00,HAND TRIPPED
1282,1317,8-Oct-18,Tumkur,220,KB CROSS 220kV- NELAMANGALA,KBCROSS_220,9:10,19:32,10:21,LINE CLEAR AVILED
1283,1318,8-Oct-18,Tumkur,220,KB CROSS 220kV- SHIMOGA,MRSMG_220,12:01,16:38,4:37,ON LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2018\OCT 2018\16_to_22_OCT_2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,16-Oct-18,BAGALKOT,220,ATHANI-MAHALINGAPUR,ATHANI_220,19:47,20:37,0:50,LINE FAULT
1,2,16-Oct-18,BAGALKOT,220,ATHANI-MAHALINGAPUR,ATHANI_220,23:19,23:59,0:40,LINE FAULT
2,3,16-Oct-18,BAGALKOT,110,AMBEWADI-NK2,KAVALWADA_110,9:39,13:39,4:00,LINE CLEAR AVAILED
3,4,16-Oct-18,BAGALKOT,110,AMBEWADI-NK1,HALIYAL_110,0:00,13:57,13:57,LINE CLEAR AVAILED
4,5,16-Oct-18,BAGALKOT,110,SUPA1-AMBEWADI,AMBEWADI_220,11:40,13:44,2:04,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
1010,1037,22-Oct-18,TUMKUR,66,TR-1,RAMPURA_66,13:23,13:35,0:12,LINE CLEAR AVAILED
1011,1038,22-Oct-18,TUMKUR,66,TR-2,RAMPURA_66,14:17,14:29,0:11,LINE CLEAR AVAILED
1012,1039,22-Oct-18,TUMKUR,66,SHYLAPURA- MADHUGIRI,"SHYLAPURA_66, YNHOSKOTE_66,\rMANGALWADA_66",8:53,8:57,0:04,HAND TRIPPED
1013,1040,22-Oct-18,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,10:22,14:46,4:23,LINE FAULT
1014,1041,22-Oct-18,TUMKUR,66,MELEKOTE HEBBUR-THIMMASANDRA,THIMMASANDRA_66,10:43,10:57,0:13,MAIN SUPPLY FAILURE

C:\C-STEP FOLDER\Transmission outage\2018\OCT 2018\23to29oct2018.pdf

,0,1,2,3,4,5,6,7,8,9
0,1.0,23-Oct-18,Bagalkot,110.0,"110/11KV,HV1",ACHANUR_110,18:23,18:36,0:13,LOAD CURTAILMENT
1,2.0,23-Oct-18,Bagalkot,110.0,"110/11KV,HV2",AINAPUR_110,18:23,18:29,0:06,LOAD CURTAILMENT
2,3.0,23-Oct-18,Bagalkot,110.0,"110/11KV,HV2",AINAPUR_110,18:31,18:40,0:09,LOAD CURTAILMENT
3,4.0,23-Oct-18,Bagalkot,110.0,"110/11KV,HV1",ATHARGA_110,18:24,18:37,0:13,LOAD CURTAILMENT
4,5.0,23-Oct-18,Bagalkot,110.0,"110/33KV,HV3",UGAR KHUD_110,20:06,20:09,0:03,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
960,933.0,29-Oct-18,TUMKUR,66.0,TELAGI- VESTAS IPP,VESTAS_IPP_66,8:50,8:56,0:05,LINE CLEAR AVAILED
961,934.0,29-Oct-18,TUMKUR,66.0,THALLAK 220kV- GOWRASAMUDRA,GOWRASAMUDRA_66,11:21,11:53,0:32,HAND TRIPPED
962,935.0,29-Oct-18,TUMKUR,66.0,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,12:06,14:43,2:36,LINE FAULT
963,936.0,29-Oct-18,TUMKUR,66.0,TR-1,YNHOSKOTE_66,11:45,12:41,0:56,LINE CLEAR AVAILED
964,937.0,29-Oct-18,TUMKUR,66.0,TR-2,YNHOSKOTE_66,12:43,13:17,0:33,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2018\OCT 2018\30&31oct2018_to_05nov2018.pdf

,0,1,2,3,4,5,6,7,8,9,10
0,1,30-Oct-18,BAGALKOT,110,"110/11KV, HV1",NaN,TORVI(BIJAPUR)_110,11:05,12:08,1:03,LINE CLEAR AVAILED
1,2,30-Oct-18,BAGALKOT,110,TORVI(BIJAPUR)-BHUTANAL,NaN,BHUTANAL_110,12:05,12:07,0:02,LINE FAULT
2,3,30-Oct-18,BAGALKOT,110,CHIKKODI220-KHADAKALAT,NaN,"KHADAKALAT_110,NIPPANI_110",8:25,8:39,0:14,LINE FAULT
3,4,30-Oct-18,BAGALKOT,220,GHTAPRABHA-KUDACHI,NaN,GHATAPRABHA_220,12:13,21:45,9:32,LINE FAULT
4,5,30-Oct-18,BAGALKOT,220,KUDACHI-GHATAPRABHA,NaN,KUDACHI_220,16:48,21:45,4:57,NBFC ISSUED
...,...,...,...,...,...,...,...,...,...,...,...
905,850,5-Nov-18,TUMKUR,66,TR-1 & TR-2(LV SIDE),MADHUGIRI_220,12:36,13:01,0:25,HAND TRIPPED,None
906,851,5-Nov-18,TUMKUR,66,TR-1,NEELAGUNDA_220,0:27,0:34,0:06,TRANSFORMER FAULT,None
907,852,5-Nov-18,TUMKUR,66,SIRA- MADHUGIRI 2,"BUKKAPATNA_66,\rKALLAMBELLA_66",8:42,8:57,0:15,LINE FAULT,None
908,853,5-Nov-18,TUMKUR,66,TR-1,THIMMASANDRA_66,12:35,14:00,1:25,LINE CLEAR AVAILED,None
909,854,5-Nov-18,TUMKUR,66,TR-1,YEDIYUR_66,16:05,16:37,0:31,LINE CLEAR AVAILED,None

C:\C-STEP FOLDER\Transmission outage\2018\OCT 2018\9-15.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,9-Oct-18,Bagalkot,110,"110/11KV, HV1",AREMALLAPUR_110,9:15,15:03,5:48,HAND TRIPPED
1,2,9-Oct-18,Bagalkot,110,ATHANI220- AIGALI,AIGALI_110,7:07,7:19,0:12,LINE FAULT
2,3,9-Oct-18,Bagalkot,110,"110/11KV, HV1",THORVI_110,7:40,7:58,0:18,TRANSFORMER FAULT
3,4,9-Oct-18,Bagalkot,110,"110/33KV, HV1",KADANAKOPPA_110,9:01,13:09,4:08,TRANSFORMER FAULT
4,5,9-Oct-18,Bagalkot,110,"110/33KV, HV2",GULEDGUDDA_110,7:16,7:25,0:09,TRANSFORMER FAULT
...,...,...,...,...,...,...,...,...,...,...
938,972,15-Oct-18,Tumkur,66,KUKKAWADA- LINGADAHALLI,PULAMG_66,17:27,17:39,0:12,LINE FAULT
939,973,15-Oct-18,Tumkur,66,TR-1,NAGASAMUDRA_66,13:41,13:45,0:04,TRANSFORMER FAULT
940,974,15-Oct-18,Tumkur,66,NEELAGUNDA 220kV-\rPUNABHAGHATTA,"PUNABHAGHATTA_66,\rPALLAGATTE_66,\rUCHCHANGIDU...",15:30,15:36,0:05,HAND TRIPPED
941,975,15-Oct-18,Tumkur,66,TR-2,TUMKUR_66,10:21,17:21,7:00,LINE CLEAR AVAILED
942,976,15-Oct-18,Tumkur,66,TR-1,YNHOSKOTE_66,9:28,9:39,0:10,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2019\APR 2019\02APR2019to08APR2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,2-Apr-19,BAGALKOT,110,"110/11KV,HV-1",ANAND NAGAR_110,10:30,16:38,6:08,LINE CLEAR AVAILED
1,2,2-Apr-19,BAGALKOT,110,HUNAGUND -B.BAGEWADI(KUDALASANGAM),KUDALASANGAM_110,10:33,10:38,0:05,LOAD CHANGEOVER
2,3,2-Apr-19,BAGALKOT,110,KADANAKOPPA-KAVALAWAD,KAVALAWAD_110,6:46,7:29,0:43,LINE FAULT
3,4,2-Apr-19,BAGALKOT,220,BIDNAL-NARENDRA,BIDNAL_220,11:14,14:46,3:32,NFBC ISSUED
4,5,2-Apr-19,BAGALKOT,220,BIDNAL-HARTI 2,BIDNAL_220,7:42,13:39,5:57,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
740,708,8-Apr-19,TUMKUR,66,BADDIHALLI- MELEKOTE,BADDIHALLI_66,12:52,15:19,2:26,LINE CLEAR AVAILED
741,709,8-Apr-19,TUMKUR,66,HIREHALLI - MELEKOTE,HIREHALLY_66,15:07,15:14,0:07,LINE FAULT
742,710,8-Apr-19,TUMKUR,66,TR-1( LV1),HONNALLI_220,13:00,13:12,0:12,HAND TRIPPED
743,711,8-Apr-19,TUMKUR,66,HONNALLI 220kV- CHANNAGIRI,"CHANNAGIRI_66, DEVARAHALLI_66,\rBENKIKERE_66, ...",12:57,13:11,0:13,HAND TRIPPED
744,712,8-Apr-19,TUMKUR,66,HONNALLI 220KV- SASUVEHALLI,SASUVEHALLI_66,12:57,13:12,0:15,HAND TRIPPED

C:\C-STEP FOLDER\Transmission outage\2019\APR 2019\09APR2019to15APR2019.pdf

,0,1,2,3,4,5,6,7,8,9,10,11
0,1,9-Apr-19,BAGALKOT,220,BIDNAL-HAVERI,BIDNAL_220,15:26,15:51,0:25,LINE CLEAR AVAILED,NaN,NaN
1,2,9-Apr-19,BAGALKOT,110,"110/33KV,HV2","GULEDAGUDDA_110,KAMATAGI_33",14:18,14:41,0:23,HAND TRIPPED,NaN,NaN
2,3,9-Apr-19,BAGALKOT,110,"110/33KV,HV2","GULEDAGUDDA_110,KAMATAGI_33",16:01,16:32,0:31,HAND TRIPPED,NaN,NaN
3,4,9-Apr-19,BAGALKOT,220,HAVERI-GUTTUR 1,HAVERI_220,10:48,13:09,2:21,LINE CLEAR AVAILED,NaN,NaN
4,5,9-Apr-19,BAGALKOT,220,HAVERI-GUTTUR 2,HAVERI_220,13:10,13:47,0:37,LINE CLEAR AVAILED,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
747,748,15-Apr-19,MYSORE,66,HV2,BOOKANAKERE_66,17:19,17:53,0:34,LINE CLEAR AVAILED,NaN,NaN
748,749,15-Apr-19,MYSORE,66,CR NAGARA-CHANDAKAVADI,CHANDAKAVADI_66,13:33,23:59,10:25,LINE CLEAR AVAILED,NaN,NaN
749,750,15-Apr-19,MYSORE,66,MADHUVANAHALLI-KOLLEGALA 1,BGPURA_66 KOLLEGALA_66\rPARINAMIPURA_66 SATHEG...,6:01,6:10,0:08,LINE FAULT,NaN,NaN
750,751,15-Apr-19,MYSORE,66,HV1,SANTHESARAGUR_66,15:40,15:43,0:03,TRANSFORMER FAULT,NaN,NaN
751,752,15-Apr-19,MYSORE,66,HV5,SFCSHIVA_66,16:02,22:55,6:52,LINE CLEAR AVAILED,NaN,NaN

C:\C-STEP FOLDER\Transmission outage\2019\APR 2019\16APR2019to22APR2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,16-Apr-19,BAGALKOT,110,"110/11KV,HV2",YARAGATTI_110,20:05,20:11,0:06,TRANSFORMER FAULT
1,2,16-Apr-19,BAGALKOT,110,HUBLI220-KADANKOPPA,KADANKOPPA_110,10:32,13:58,3:26,LINE CLEAR AVAILED
2,3,16-Apr-19,BAGALKOT,110,"110/11KV,HV1",SHIRGOAN_110,8:10,9:23,1:13,LINE CLEAR AVAILED
3,4,16-Apr-19,BAGALKOT,110,"110/11KV,HV2",MALGHAN(B)_110,21:49,21:59,0:10,TRANSFORMER FAULT
4,5,16-Apr-19,BAGALKOT,220,"220/110KV, HV1&LV1",KARWAR_220,10:31,12:00,1:29,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
470,471,22-Apr-19,TUMKUR,66,TR-2,HONNALI_66,9:28,10:39,1:11,TRANSFORMER FAULT
471,472,22-Apr-19,TUMKUR,66,TR-2,HONNALI_66,10:50,11:36,0:45,TRANSFORMER FAULT
472,473,22-Apr-19,TUMKUR,66,TR-1,LINGDHALLI_66,20:36,20:40,0:03,TRANSFORMER FAULT
473,474,22-Apr-19,TUMKUR,66,TR-1,MADHUGIRI_220,16:09,17:03,0:53,LINE CLEAR AVAILED
474,475,22-Apr-19,TUMKUR,66,THALLAK 220kV- CHALLAKERE 1,"CHALLAKERE_66, SANIKERE_66",14:57,15:26,0:29,HAND TRIPPED

C:\C-STEP FOLDER\Transmission outage\2019\APR 2019\23APR2019to29APR2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,23-Apr-19,BAGALKOT,110,ATHANI SUGARS-AINAPUR,AINAPUR_110,5:21,5:41,0:20,LINE FAULT
1,2,23-Apr-19,BAGALKOT,110,BAGEWADI220-MAMDAPUR1,MAMADAPUR(B)_110,17:29,17:45,0:16,LINE FAULT
2,3,23-Apr-19,BAGALKOT,110,BAGEWADI220-MAMADAPUR2,MAMADAPUR(B)_110,17:29,17:45,0:16,LINE FAULT
3,4,23-Apr-19,BAGALKOT,110,"110/11KV,HV2",JAMKHANDI_110,10:48,10:55,0:07,TRANSFORMER FAULT
4,5,23-Apr-19,BAGALKOT,110,SIRSI220-UMMACHAGI,UMMACHAGI_110,14:28,16:35,2:07,LINE FAULT
...,...,...,...,...,...,...,...,...,...,...
869,870,29-Apr-19,TUMKUR,66,TR-2,HALURAMESHWARA_66,15:52,18:45,2:53,LINE CLEAR AVAILED
870,871,29-Apr-19,TUMKUR,66,TR-1,HARIHAR_66,20:21,20:26,0:05,TRANSFORMER FAULT
871,872,29-Apr-19,TUMKUR,66,NEELAGUNDA 220kV- PUNABHAGHATTA,"PUNABHAGHATTA_66,HARAPPANAHALLI_\r66,HALUVAGAL...",19:13,20:25,1:11,LINE FAULT
872,873,29-Apr-19,TUMKUR,66,TR-1,SAVALANGA_66,15:58,19:20,3:21,MAIN SUPPLY FAILURE
873,874,29-Apr-19,TUMKUR,66,TR-1,TAVAREKERE(C)_66,16:01,16:20,0:18,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2019\APR 2019\30APR2019to06MAY2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,30-Apr-19,BAGALKOT,220,AMBEWADI-PONDA 2,AMBEWADI_220,12:17,18:42,6:25,LINE CLEAR AVAILED
1,2,30-Apr-19,BAGALKOT,220,AMBEWADI-PONDA 1,AMBEWADI_220,0:00,19:04,19:04,LINE CLEAR AVAILED
2,3,30-Apr-19,BAGALKOT,220,AMBEWADI-NARENDRA 2,AMBEWADI_220,11:11,19:45,8:34,LINE CLEAR AVAILED
3,4,30-Apr-19,BAGALKOT,110,BAGALKOT-NEERBUDIHAL(KATARAKI),NEERBUDIHAL_110,0:00,1:16,1:16,LINE CLEAR AVAILED
4,5,30-Apr-19,BAGALKOT,110,"110/33KV, HV1","MKHUBLI_110, DANDIGAWAD_33",15:03,15:15,0:12,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
942,943,6-May-19,TUMKUR,66,TR-2,BRAHMASANDRA_66,11:24,11:42,0:18,LINE CLEAR AVAILED
943,944,6-May-19,TUMKUR,66,TR-2,CHANNAGIRI_66,13:29,14:27,0:58,LINE CLEAR AVAILED
944,945,6-May-19,TUMKUR,66,TR-2,DAVANAGERE_66,21:34,21:40,0:05,TRANSFORMER FAULT
945,946,6-May-19,TUMKUR,66,DAVANGERE SRS- HARIHARA,"HARIHAR_66, HARIHAR-\rHOSPET_66, BANUVALLI_66,...",14:19,14:32,0:12,LINE FAULT
946,947,6-May-19,TUMKUR,66,MATHOD- PANCHANAHALLI,"PANCHANAHALLI_66, GARAGA_66",10:30,11:36,1:05,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2019\AUG 2019\06AUG2019_to_12AUG2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,6-Aug-19,BAGALKOT,110,"110/11KV,HV-2",AMBEWADI_220,8:48,8:50,0:02,TRANSFORMER FAULT
1,2,6-Aug-19,BAGALKOT,110,ANKOLA-KUMATA2,KUMATA_110,9:25,9:30,0:05,HAND TRIPPED
2,3,6-Aug-19,BAGALKOT,110,"110/11KV,HV1",BILAGI_110,14:56,15:25,0:29,HAND TRIPPED
3,4,6-Aug-19,BAGALKOT,220,BAGEWADI-RBRK,BAGEWADI_220,6:59,7:20,0:21,LOAD CURTAILMENT
4,5,6-Aug-19,BAGALKOT,220,BELGAUM-NARENDRA1(KANABARGI1),BELGAUM_220,13:21,23:59,10:38,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
790,791,12-Aug-19,TUMKUR,110,TR-1,TURUVEKERE_110,19:06,19:17,0:10,TRANSFORMER FAULT
791,792,12-Aug-19,TUMKUR,110,TR-1,TURUVEKERE_110,23:31,23:37,0:05,TRANSFORMER FAULT
792,793,12-Aug-19,TUMKUR,66,TR-1,KORA_66,19:29,19:36,0:07,TRANSFORMER FAULT
793,794,12-Aug-19,TUMKUR,66,TR-2,MAVINAKATTE_66,12:04,12:22,0:17,LINE CLEAR AVAILED
794,795,12-Aug-19,TUMKUR,66,TR-1,TUMKUR_66,17:15,18:02,0:46,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2019\AUG 2019\13AUG2019_to_19AUG2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,13-Aug-19,BAGALKOT,220,"220/110KV,HV2&LV2",BAGALKOT_220,10:33,14:12,3:39,LINE CLEAR AVAILED
1,2,13-Aug-19,BAGALKOT,110,GADAG -BETAGERI,BETAGERI_110,10:47,13:55,3:08,LINE CLEAR AVAILED
2,3,13-Aug-19,BAGALKOT,220,BELGAUM-NARENDRA2,BELGAUM_220,0:00,8:46,8:46,LINE CLEAR AVAILED
3,4,13-Aug-19,BAGALKOT,220,CHIKKODI-TALANDAGE(KOLHAPUR1),CHIKKODI_220,11:55,16:32,4:37,LINE CLEAR AVAILED
4,5,13-Aug-19,BAGALKOT,220,CHIKKODI-MUDASINGI(KOLHAPUR2),CHIKKODI_220,12:06,16:42,4:36,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
524,525,19-Aug-19,TUMKUR,66,HONNALLI 220kV- CHANNAGIRI(NALLUR ),"CHANNAGIRI_66, DEVARAHALLI_66,\rBENKIKERE_66, ...",15:32,17:39,2:07,LINE CLEAR AVAILED
525,526,19-Aug-19,TUMKUR,66,JAVAGONDANAHALLI- INFOSYS-1,INFOSYS1_EHT_66,10:56,11:05,0:09,LINE FAULT
526,527,19-Aug-19,TUMKUR,66,TR-1,MAVINAKATTE_66,22:41,22:51,0:10,TRANSFORMER FAULT
527,528,19-Aug-19,TUMKUR,66,RANGENAHALLI- BORUKHASOLAR,BORUKHASOLAR_IPP_66,15:06,15:18,0:12,MAIN SUPPLY FAILURE
528,529,19-Aug-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,7:53,8:06,0:12,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\AUG 2019\20AUG2019_to_26AUG2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,20-Aug-19,BAGALKOT,110,SIRSI220-UMMACHAGI,UMMACHAGI_110,0:00,13:37,13:37,LINE CLEAR AVAILED
1,2,20-Aug-19,BAGALKOT,110,RON-HIREHAL,HIREHAL_110,1:18,8:34,7:16,LINE FAULT
2,3,20-Aug-19,BAGALKOT,220,NAGJHARI3-HUBLI,HUBLI_220,10:20,11:44,1:24,LINE FAULT
3,4,20-Aug-19,BAGALKOT,220,NAGJHARI1-HUBLI,HUBLI_220,10:17,17:24,7:07,LINE CLEAR AVAILED
4,5,20-Aug-19,BAGALKOT,220,HUBLI-SIRSI2,HUBLI_220,13:33,23:59,10:26,LINE FAULT
...,...,...,...,...,...,...,...,...,...,...
554,555,26-Aug-19,HASSAN,220,VARAHI-SHMG3,varahi_gen,9:25,19:01,9:36,NFBC ISSUED
555,556,26-Aug-19,HASSAN,66,HV1,ALDUR_66,12:00,23:59,11:59,LINE CLEAR AVAILED
556,557,26-Aug-19,MYSORE,66,HV1,ELAVALA_66,11:14,15:42,4:28,LINE CLEAR AVAILED
557,558,26-Aug-19,MYSORE,66,KUSHALANAGRA 220-BETTADAPURA,"BETTADHAPURA_66,\rCHUNCHUNKATTE_66, KITTUR_66,...",23:04,23:13,0:08,LINE FAULT
558,559,26-Aug-19,MYSORE,66,HV1,PGPALYA_66,13:21,15:22,2:00,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2019\AUG 2019\27AUG2019_to_02SEP2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,27-Aug-19,BAGALKOT,110,SOUDATTI220-SOUDATTI1,SOUDATTI_110,9:07,13:23,4:16,LINE CLEAR AVAILED
1,2,27-Aug-19,BAGALKOT,110,SOUDATTI220-RAMADURG1,RAMADURG_110,9:05,13:24,4:19,LINE CLEAR AVAILED
2,3,27-Aug-19,BAGALKOT,110,"110/11KV,HV1",SIRSI_110,11:23,11:25,0:02,HAND TRIPPED
3,4,27-Aug-19,BAGALKOT,110,"110/11KV,HV2",SANKESHWAR_110,10:11,17:34,7:23,LINE CLEAR AVAILED
4,5,27-Aug-19,BAGALKOT,110,"110/11KV,HV1",SAIDAPUR_110,10:20,10:28,0:08,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
443,444,2-Sep-19,GULBARGA,110,SHAHPUR-KHANAPUR,KHANAPUR_GLB_110,21:27,21:34,0:07,LINE FAULT
444,445,2-Sep-19,HASSAN,66,BAGUR-RAMAPUR,BAGUR_66,11:37,11:47,0:10,LINE FAULT
445,446,2-Sep-19,HASSAN,66,BAGUR-RAMAPUR,BAGUR_66,12:30,12:35,0:05,LINE FAULT
446,447,2-Sep-19,MYSORE,66,BG NAGARA-YEDIYURU,"ADICHUNCHANAGIRI_66, VADERALLI _66",4:55,5:11,0:16,LINE FAULT
447,448,2-Sep-19,TUMKUR,66,NEELAGUNDA- TELAGI,"TELAGI_66, KURUBARAHALLI_66,\rYARAGUNTA_66, OB...",21:14,23:57,2:42,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\AUG 2019\30JULY2019_to_05_AUG_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,30-Jul-19,BAGALKOT,110,"110/33KV,HV3","BAGEWADI_220,MUTTAGI_33,M\rANAGULI_33",7:00,18:45,11:45,TRANSFORMER FAULT
1,2,30-Jul-19,BAGALKOT,110,ATHANI220-AIGALI,AIGALI_110,0:00,0:17,0:17,LINE CLEAR AVAILED
2,3,30-Jul-19,BAGALKOT,110,ATHANI220-AIGALI,AIGALI_110,2:12,2:22,0:10,LINE FAULT
3,4,30-Jul-19,BAGALKOT,220,BELGAUM-CHIKKODI 2,BELGAUM_220,1:05,7:30,6:25,LINE CLEAR AVAILED
4,5,30-Jul-19,BAGALKOT,220,BELGAUM-CHIKKODI 2,BELGAUM_220,20:34,23:59,3:25,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
522,523,5-Aug-19,TUMKUR,66,TR-2,BADAVANAHALLI_66,20:23,20:30,0:07,TRANSFORMER FAULT
523,524,5-Aug-19,TUMKUR,66,HIRIYUR 220KV- ENERCON-1,ENERCON1_IPP_66,17:54,17:59,0:05,HAND TRIPPED
524,525,5-Aug-19,TUMKUR,66,HONNALLI 220KV- KUNDUR,"KUNDUR_66,MALEBENNUR_66",16:39,16:51,0:11,LINE FAULT
525,526,5-Aug-19,TUMKUR,66,TR-1,PULAMG_66,13:19,13:28,0:09,TRANSFORMER FAULT
526,527,5-Aug-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,10:37,12:40,2:02,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\DEC 2019\03rd_dec_to_9th_dec_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,3-Dec-19,BAGALKOT,110,BIJAPUR220-ENERGAON,BIJAPUR_220,5:58,6:41,0:43,LINE FAULT
1,2,3-Dec-19,BAGALKOT,110,RON2-GAJENDRAGAD,GAJENDRAGAD_110,10:30,12:11,1:41,LINE FAULT
2,3,3-Dec-19,BAGALKOT,110,KUSTAGI-GAJENDRAGAD,GAJENDRAGAD_110,10:30,23:59,13:29,LINE CLEAR AVAILED
3,4,3-Dec-19,BAGALKOT,220,CHIKKODI-GHATAPRABHA,CHIKKODI_220,10:38,18:08,7:30,NFBC ISSUED
4,5,3-Dec-19,BAGALKOT,220,DHONI1&2-GADAG,GADAG_220,17:45,23:59,6:14,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
655,656,9-Dec-19,TUMKUR,66,NEELAGUNDA 220kV- PUNABHAGHATTA,"PUNABHAGHATTA_66,UCHCHANGID\rURGA_66,SOKKE_66,...",1:36,1:44,0:08,LINE FAULT
656,657,9-Dec-19,TUMKUR,66,NEELAGUNDA 220kV- PUNABHAGHATTA,"PUNABHAGHATTA_66,UCHCHANGID\rURGA_66,SOKKE_66,...",5:43,5:55,0:12,LINE FAULT
657,658,9-Dec-19,TUMKUR,66,PANDARAHALLI- HOLALKERE,"HOLALKERE_66,HDPURA_66,",23:17,23:24,0:07,LINE FAULT
658,659,9-Dec-19,TUMKUR,66,TR-1,PANDARAHALLI_66,16:11,16:32,0:21,LINE CLEAR AVAILED
659,660,9-Dec-19,TUMKUR,66,TR-1,PANDARAHALLI_66,17:22,17:41,0:19,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2019\DEC 2019\10th_Dec_to_16th_dec_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,10-Dec-19,BAGALKOT,110,"110/33 KV,HV 2",ANKOLA_110&33KV SEA BIRD\r&ANKOLA,15:54,19:05,3:11,LINE CLEAR AVAILED
1,2,10-Dec-19,BAGALKOT,110,"110/11KV,HV 1",ATHARGA_110,7:07,7:15,0:08,LOAD CURTAILMENT
2,3,10-Dec-19,BAGALKOT,220,BAGALKOT-GADAG 1,BAGALKOT_220,12:03,16:43,4:40,LINE CLEAR AVAILED
3,4,10-Dec-19,BAGALKOT,110,"110/11KV,HV 4",GAJENDRAGAD_110,6:49,7:05,0:16,LOAD CURTAILMENT
4,5,10-Dec-19,BAGALKOT,110,"110/11KV,HV 4",GAJENDRAGAD_110,7:12,7:41,0:29,LOAD CURTAILMENT
...,...,...,...,...,...,...,...,...,...,...
641,642,16-Dec-19,MYSORE,66,MADHUVANAHALLI-PG PALYA,PGPALYA_66,14:04,15:30,1:26,LINE CLEAR AVAILED
642,643,16-Dec-19,MYSORE,66,SANTHE SARAGURU-B MATTGERE,B MATKERE_66,10:16,18:29,8:13,NFBC ISSUED
643,644,16-Dec-19,MYSORE,66,HV1,SANTHESARAGUR_66,12:35,12:45,0:10,TRANSFORMER FAULT
644,645,16-Dec-19,MYSORE,66,HV1,SANTHESARAGUR_66,12:58,13:44,0:46,TRANSFORMER FAULT
645,646,16-Dec-19,MYSORE,66,HV1,SANTHESARAGUR_66,13:55,14:00,0:05,NaN

C:\C-STEP FOLDER\Transmission outage\2019\DEC 2019\17th_Dec_to_23rd_dec_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,17-Dec-19,BAGALKOT,110,SOUDATTI220-MUNAVALLI,MUNAVALLI_110,11:51,17:48,5:57,LINE CLEAR AVAILED
1,2,17-Dec-19,BAGALKOT,110,"110/11KV,HV2",MUKARTHAL_110,0:00,17:47,17:47,LINE CLEAR AVAILED
2,3,17-Dec-19,BAGALKOT,110,"110/11KV,HV2",HIDIKALDAM_110,12:37,12:45,0:08,HAND TRIPPED
3,4,17-Dec-19,BAGALKOT,220,NARENDRA-AMBEWADI1&2,NARENDRA_220,12:56,15:34,2:38,LINE CLEAR AVAILED
4,5,17-Dec-19,BAGALKOT,110,"110/11KV,HV2",GOPANAKOPPA_110,11:07,13:27,2:20,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
621,622,23-Dec-19,TUMKUR,66,DAVANGERE SRS- SOKKE,"MELLEKATTE_66, SOKKE_66",15:26,15:37,0:10,LINE FAULT
622,623,23-Dec-19,TUMKUR,66,MADHUGIRI 220kV- MADHUGIRI,"MADHUGIRI_66, BADAVANAHALLI_66",13:30,18:07,4:37,LINE FAULT
623,624,23-Dec-19,TUMKUR,66,MADHUGIRI 66kV- BADAVANAHALLI,MADHUGIRI_66,13:49,18:11,4:21,LINE CLEAR AVAILED
624,625,23-Dec-19,TUMKUR,66,TR-1,MADHUGIRI_66,13:49,18:11,4:22,LINE CLEAR AVAILED
625,626,23-Dec-19,TUMKUR,66,TR-2,MADHUGIRI_66,13:49,18:11,4:22,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2019\DEC 2019\24th_Dec_to_30th_dec_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,24-Dec-19,BAGALKOT,220,"220/110KV, HV1&LV1",BAGALKOT_220,10:16,14:48,4:32,LINE CLEAR AVAILED
1,2,24-Dec-19,BAGALKOT,220,"220/110KV, HV2&LV2",BAGALKOT_220,14:49,18:04,3:15,LINE CLEAR AVAILED
2,3,24-Dec-19,BAGALKOT,110,ATHANI220-BALIGERI(TAUSHI),BALIGERI(TAUSHI)_110,0:09,1:31,1:22,LINE CLEAR AVAILED
3,4,24-Dec-19,BAGALKOT,110,ATHANI220-BALIGERI(TAUSHI),BALIGERI(TAUSHI)_110,9:52,10:32,0:40,LINE CLEAR AVAILED
4,5,24-Dec-19,BAGALKOT,110,"110/11KV, HV2",BAGALKOT_110,15:41,23:59,8:18,TRANSFORMER FAULT
...,...,...,...,...,...,...,...,...,...,...
664,699,30-Dec-19,TUMKUR,66,TR-1,KORA_66,5:59,6:04,0:05,TRANSFORMER FAULT
665,700,30-Dec-19,TUMKUR,66,TR-1,MYLANAHALLI_66,6:49,7:43,0:53,TRANSFORMER FAULT
666,701,30-Dec-19,TUMKUR,66,NITRAHALLI 66 -CLEAN SOLAR,CLEANMAXSOLAR_IPP_66,14:14,14:24,0:10,LINE CLEAR AVAILED
667,702,30-Dec-19,TUMKUR,66,TR-1,PAVAGADA_66,14:05,14:46,0:40,LINE CLEAR AVAILED
668,703,30-Dec-19,TUMKUR,66,YEDIYUR- BGNAGARA_66,BGNAGARA_66,15:10,15:15,0:05,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2019\DEC 2019\26th_nov_to_2nd_dec_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,26-Nov-19,BAGALKOT,220,AMBEWADI-NAGJARI2,AMBEWADI_220,14:13,23:59,9:46,LINE FAULT
1,2,26-Nov-19,BAGALKOT,220,GUTUUR1-HAVERI,HAVERI_220,15:32,17:30,1:58,LINE CLEAR AVAILED
2,3,26-Nov-19,BAGALKOT,220,GUTUUR2-HAVERI,HAVERI_220,10:40,12:28,1:48,LINE CLEAR AVAILED
3,4,26-Nov-19,BAGALKOT,110,ATHANI220-SATTI,SATTI_220,11:00,15:07,4:07,LINE CLEAR AVAILED
4,5,26-Nov-19,BAGALKOT,110,MK HUBLI220-BAILHONGAL,BAILHONGAL_110,15:40,15:45,0:05,LINE FAULT
...,...,...,...,...,...,...,...,...,...,...
682,683,2-Dec-19,TUMKUR,66,TR-1,CHANNAGIRI_66,16:45,16:58,0:12,TRANSFORMER FAULT
683,684,2-Dec-19,TUMKUR,66,DAVANGERE SRS- SOKKE,"MELLEKATTE_66, SOKKE_66",14:05,14:27,0:21,LINE FAULT
684,685,2-Dec-19,TUMKUR,66,GULIGENAHALLI- SIRA 2,SIRA_66,5:30,5:35,0:05,LINE FAULT
685,686,2-Dec-19,TUMKUR,66,HONNALLI 220kV- BANUVALLI,"BANUVALLI_66, NANDIGUDI_66, KARGIL_EH",11:12,11:32,0:20,LINE FAULT
686,687,2-Dec-19,TUMKUR,66,URDIGERE-ANTHRASANAHALLI,URDIGERE_66,11:43,14:34,2:50,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2019\DEC 2019\31st_Dec_to_6th_Jan_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,31-Dec-2019,BAGALKOT,110,"110/11KV,HV1",ATHARGA_110,7:15,7:26,0:11,LOAD CURTAILMENT
1,2,31-Dec-2019,BAGALKOT,220,PONDA1-AMBEWADI,AMBEWADI_220,0:00,14:12,14:12,LINE CLEAR AVAILED
2,3,31-Dec-2019,BAGALKOT,220,NAGJHARI2-AMBEWADI,AMBEWADI_220,10:18,10:32,0:14,LINE FAULT
3,4,31-Dec-2019,BAGALKOT,220,NAGJHARI1-AMBEWADI,AMBEWADI_220,10:51,18:32,7:41,LINE CLEAR AVAILED
4,5,31-Dec-2019,BAGALKOT,220,NAGJHARI1-AMBEWADI,AMBEWADI_220,15:23,18:33,3:10,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
661,662,6-Jan-20,TUMKUR,66,MADHUGIRI 220kV- MADHUGIRI,"MADHUGIRI_66, BADAVANAHALLI_66",17:12,17:20,0:08,LOAD CURTAILMENT
662,663,6-Jan-20,TUMKUR,66,TR-2,HIREHALLY_66,10:10,10:21,0:11,TRANSFORMER FAULT
663,664,6-Jan-20,TUMKUR,66,KATTIGE- BEDRUGADDE,KATTIGE_66,15:00,15:49,0:48,MAIN SUPPLY FAILURE
664,665,6-Jan-20,TUMKUR,66,TR-1,KATTIGE_66,15:00,15:49,0:48,MAIN SUPPLY FAILURE
665,666,6-Jan-20,TUMKUR,66,KATTIGE- RENEW WIND IPP,RENEW WIND ENERGY_IPP_66,15:00,15:53,0:52,MAIN SUPPLY FAILURE

C:\C-STEP FOLDER\Transmission outage\2019\FEB 2019\05FEB2019to11FEB2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,5-Feb-19,BAGALKOT,110,"110/11KV,HV-2",AREMALLAPUR_110,12:31,14:14,1:43,HAND TRIPPED
1,2,5-Feb-19,BAGALKOT,110,BETAGERI-NAREGAL,BETAGERI_110,8:19,19:02,10:43,HAND TRIPPED
2,3,5-Feb-19,BAGALKOT,110,GADAG- BETAGERI,BETAGERI_110,10:28,19:02,8:34,HAND TRIPPED
3,4,5-Feb-19,BAGALKOT,110,"110/11KV,HV-1",BETAGERI_110,10:28,19:02,8:34,HAND TRIPPED
4,5,5-Feb-19,BAGALKOT,220,"220/110KV,HV&LV-1",GADAG_220,11:01,23:59,12:58,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
823,824,11-Feb-19,TUMKUR,66,TAVAREKERE (H)-HIRIYUR,TAVAREKERE(H)_66,15:08,17:13,2:05,MAIN SUPPLY FAILURE
824,825,11-Feb-19,TUMKUR,66,RANGENAHALLI -AZURESOLAR,AZURESOLAR_IPP_66,10:52,16:03,5:10,MAIN SUPPLY FAILURE
825,826,11-Feb-19,TUMKUR,66,RANGENAHALLI- BORUKHASOLAR,BORUKHASOLAR_IPP_66,10:52,11:30,0:38,MAIN SUPPLY FAILURE
826,827,11-Feb-19,TUMKUR,66,RANGANATHAPURA-\rDYVARANAHALLI,RANGENAHALLI_66,10:52,18:17,7:25,MAIN SUPPLY FAILURE
827,828,11-Feb-19,TUMKUR,66,RANGANATHAPURA-HIRIYUR,RANGENAHALLI_66,10:52,18:17,7:25,MAIN SUPPLY FAILURE

C:\C-STEP FOLDER\Transmission outage\2019\FEB 2019\12FEB2019to18FEB2019.pdf

,0,1,2,3,4,5,6,7,8,9,10
0,1,12-Feb-19,BAGALKOT,110,AMBEWADI-NK2(KAVALWADA),KAWALWAD_110,14:39,15:14,0:35,LINE CLEAR AVAILED,None
1,2,12-Feb-19,BAGALKOT,110,AMBEWADI-NK1(HALIYAL),HALIYAL_110,14:41,23:59,9:18,LINE FAULT,None
2,3,12-Feb-19,BAGALKOT,110,AMBEWADI-SUPA2,AMBEWADI_220,14:58,15:25,0:27,LINE CLEAR AVAILED,None
3,4,12-Feb-19,BAGALKOT,110,AMBEWADI-SUPA1,AMBEWADI_220,14:58,15:15,0:17,LINE CLEAR AVAILED,None
4,5,12-Feb-19,BAGALKOT,110,"110/33KV,HV3","ANKALI_110,NANDIKURALI 33KV",9:39,14:48,5:09,LINE CLEAR AVAILED,None
...,...,...,...,...,...,...,...,...,...,...,...
1215,1094,18-Feb-19,TUMKUR,66,TR-1,KATTIGE_66,11:02,12:05,1:02,TRANSFORMER FAULT,None
1216,1095,18-Feb-19,TUMKUR,66,TR-2,MALEBENNUR_66,8:57,9:11,0:13,TRANSFORMER FAULT,None
1217,1096,18-Feb-19,TUMKUR,66,NEELAGUNDA- TELAGI,"TELAGI_66, KURUBARAHALLI_66,\rYARAGUNTA_66, OB...",20:28,21:03,0:35,LINE FAULT,None
1218,1097,18-Feb-19,TUMKUR,66,TR-1,SAVALANGA_66,16:49,17:02,0:12,LINE CLEAR AVAILED,None
1219,1098,18-Feb-19,TUMKUR,66,TR-2,TAVAREKERE(H)_66,8:22,9:52,1:29,TRANSFORMER FAULT,None

C:\C-STEP FOLDER\Transmission outage\2019\FEB 2019\19FEB2019to25FEB2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,19-Feb-19,BAGALKOT,110,"110/11KV, HV1",ACHANUR_110,17:43,17:47,0:04,LOAD CURTAILMENT
1,2,19-Feb-19,BAGALKOT,110,"110/11KV, HV2",AINAPUR_110,17:43,17:46,0:03,LOAD CURTAILMENT
2,3,19-Feb-19,BAGALKOT,110,"110/11KV, HV2",AREMALLAPUR_110,17:46,17:55,0:09,LOAD CURTAILMENT
3,4,19-Feb-19,BAGALKOT,110,"110/11KV, HV1",ATHARGA_110,17:43,18:01,0:18,LOAD CURTAILMENT
4,5,19-Feb-19,BAGALKOT,110,"110/33KV, HV3","BAGALKOT_220, KATGERI_33",17:45,18:06,0:21,LOAD CURTAILMENT
...,...,...,...,...,...,...,...,...,...,...
1053,1054,25-Feb-19,TUMKUR,66,DYAVARANAHALLI-RANGENAHALLI (P R\rPURA),"PRPURA_66, LINGADAHALLI_TMK2_66",8:05,17:53,9:48,LINE CLEAR AVAILED
1054,1055,25-Feb-19,TUMKUR,66,TR-1,HARAPPANAHALLI_66,12:04,17:10,5:05,LINE CLEAR AVAILED
1055,1056,25-Feb-19,TUMKUR,66,HARAPPANAHALLI-ITTAGI,HARAPPANAHALLI_66,16:00,17:16,1:16,LINE CLEAR AVAILED
1056,1057,25-Feb-19,TUMKUR,66,MADHUGIRI 66kV- BADAVANAHALLI,BADAVANAHALLI_66,10:52,11:40,0:48,MAIN SUPPLY FAILURE
1057,1058,25-Feb-19,TUMKUR,66,MATHOD- AVNTI_SLR_IPP_66,AVNTI_SLR_IPP_66,6:29,7:57,1:28,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\FEB 2019\26FEB2019to04MAR2019.pdf

,0,1,2,3,4,5,6,7,8,9,10
0,1.0,26-Feb-19,BAGALKOT,110.0,"110/11KV,HV1",ACHANUR_110,19:11,19:16,0:05,LOAD CURTAILMENT,None
1,2.0,26-Feb-19,BAGALKOT,110.0,"110/11KV,HV1",ACHANUR_110,20:02,20:30,0:28,LOAD CURTAILMENT,None
2,3.0,26-Feb-19,BAGALKOT,110.0,"110/11KV,HV2",AINAPU_110,19:11,19:14,0:03,LOAD CURTAILMENT,None
3,4.0,26-Feb-19,BAGALKOT,110.0,"110/11KV,HV1",ATHARGA_110,19:02,19:16,0:14,LOAD CURTAILMENT,None
4,5.0,26-Feb-19,BAGALKOT,110.0,"110/11KV,HV1",ATHARGA_110,20:02,20:15,0:13,LOAD CURTAILMENT,None
...,...,...,...,...,...,...,...,...,...,...,...
857,827.0,04-Mar-19,TUMKUR,66.0,DAVANGERE SRS- KUKKAWADA,"BASAVAPATNA_66,",13:25,13:38,0:13,LINE FAULT,None
858,NaN,NaN,NaN,NaN,NaN,SANTEBENNUR_66,NaN,NaN,NaN,NaN,None
859,NaN,NaN,NaN,NaN,NaN,"KUKKAWADA_66, TYAVANAGI_66,",NaN,NaN,NaN,NaN,None
860,828.0,04-Mar-19,TUMKUR,66.0,DAVANGERE SRS- KUKKAWADA,"BASAVAPATNA_66,",22:23,22:34,0:10,LINE FAULT,None
861,NaN,NaN,NaN,NaN,NaN,SANTEBENNUR_66,NaN,NaN,NaN,NaN,None

C:\C-STEP FOLDER\Transmission outage\2019\FEB 2019\29JAN2019to04FEB2019.pdf

,0,1,2,3,4,5,6,7,8,9,10
0,1.0,29-Jan-19,BAGALKOT,110.0,BAGEWADI220-MAMADAPUR1,MAMADAPUR_110,11:40,17:58,6:18,LINE CLEAR AVAILED,None
1,2.0,29-Jan-19,BAGALKOT,220.0,"220/110KV,HV1,LV1",KARWAR_220,0:00,17:20,17:20,LINE CLEAR AVAILED,None
2,3.0,29-Jan-19,BAGALKOT,110.0,"110/33KV,HV4","GOPANAKOPPA_110,KMC_33",12:31,13:50,1:19,LINE CLEAR AVAILED,None
3,4.0,29-Jan-19,BAGALKOT,110.0,CHIKKODI220-NANADI,NANADI_110,15:31,17:30,1:59,HAND TRIPPED,None
4,5.0,29-Jan-19,BANGALORE,66.0,HV2,ADDAGAL,11:32,12:40,1:07,LINE CLEAR AVAILED,None
...,...,...,...,...,...,...,...,...,...,...,...
559,536.0,4-Feb-19,TUMKUR,66.0,HANAGAL- AVADASOLAR_IPP_66,AVADASOLAR_IPP_66,16:49,19:45,2:55,LINE CLEAR AVAILED,None
560,537.0,4-Feb-19,TUMKUR,66.0,SHYLAPURA- MADHUGIRI,"SHYLAPURA_66, YNHOSKOTE_66,\rMANGALWADA_66",9:00,9:04,0:04,HAND TRIPPED,None
561,538.0,4-Feb-19,TUMKUR,66.0,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,9:49,11:53,2:04,LINE FAULT,None
562,539.0,4-Feb-19,TUMKUR,66.0,TR-1,SIRA_66,12:35,13:09,0:33,LINE CLEAR AVAILED,None
563,540.0,4-Feb-19,TUMKUR,66.0,TR-2,SIRA_66,13:14,13:32,0:17,LINE CLEAR AVAILED,None

C:\C-STEP FOLDER\Transmission outage\2019\JAN 2019\01to07JAN2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,1-Jan-19,BAGALKOT,110,"110/11KV,HV2",AMBEWADI_220,10:18,14:31,4:13,LINE CLEAR AVAILED
1,2,1-Jan-19,BAGALKOT,110,SUPA2-AMBEWADI,AMBEWADI_220,10:32,12:26,1:54,LINE CLEAR AVAILED
2,3,1-Jan-19,BAGALKOT,110,SUPA1-AMBEWADI,AMBEWADI_220,12:37,14:30,1:53,LINE CLEAR AVAILED
3,4,1-Jan-19,BAGALKOT,110,"110/11KV,HV1",DAMBAL_110,8:16,8:27,0:11,TRANSFORMER FAULT
4,5,1-Jan-19,BAGALKOT,110,GADAG220-DAMBAL2,DAMBAL_110,6:42,11:31,4:49,LINE FAULT
...,...,...,...,...,...,...,...,...,...,...
889,890,7-Jan-19,TUMKUR,66,TR-1 & TR-2,HULIYURDURGA_66,14:26,15:59,1:33,LINE CLEAR AVAILED
890,891,7-Jan-19,TUMKUR,66,TR-1,MALLASANDRA_66,10:03,10:09,0:05,TRANSFORMER FAULT
891,892,7-Jan-19,TUMKUR,66,NAGALAMADIKE-MADHUGIRI,NAGALMADIKE_66,10:16,10:25,0:08,LINE FAULT
892,893,7-Jan-19,TUMKUR,66,NAGALAMADIKE- ATRIA_IPP_66,ATRIA_IPP_66,10:49,10:53,0:03,HAND TRIPPED
893,894,7-Jan-19,TUMKUR,66,TR-1,SASALUHALLA_66,7:06,7:16,0:10,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2019\JAN 2019\08to14JAN2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1.0,8-Jan-19,BAGALKOT,220.0,BAGALKOT-VAJRAMATTI 2,BAGALKOT_220,16:32,16:50,0:18,MAIN SUPPLY FAILURE
1,2.0,8-Jan-19,BAGALKOT,220.0,BAGALKOT-GADAG 1,BAGALKOT_220,16:32,18:05,1:33,MAIN SUPPLY FAILURE
2,3.0,8-Jan-19,BAGALKOT,110.0,BAGALKOT220-BAGALKOT 2,BAGALKOT_110,16:32,16:33,0:01,MAIN SUPPLY FAILURE
3,4.0,8-Jan-19,BAGALKOT,110.0,BAGALKOT-NAVANAGAR 1,NAVANAGAR_110,16:32,16:47,0:15,MAIN SUPPLY FAILURE
4,5.0,8-Jan-19,BAGALKOT,110.0,BAGALKOT- GULEDGUDD,GULEDGUDD_110,16:32,16:33,0:01,MAIN SUPPLY FAILURE
...,...,...,...,...,...,...,...,...,...,...
782,753.0,14-Jan-19,TUMKUR,66.0,TR-1,KORA_66,11:06,11:08,0:02,TRANSFORMER FAULT
783,754.0,14-Jan-19,TUMKUR,66.0,TR-1,MADHUGIRI_66,13:02,13:09,0:07,TRANSFORMER FAULT
784,755.0,14-Jan-19,TUMKUR,66.0,TR-1,TAVAREKERE(C)_66,13:41,13:56,0:14,MAIN SUPPLY FAILURE
785,756.0,14-Jan-19,TUMKUR,66.0,TR-1,TAVAREKERE(C)_66,16:15,17:20,1:04,MAIN SUPPLY FAILURE
786,757.0,14-Jan-19,TUMKUR,66.0,TR-2,TAVAREKERE(C)_66,16:52,17:20,0:28,MAIN SUPPLY FAILURE

C:\C-STEP FOLDER\Transmission outage\2019\JAN 2019\15to21JAN2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,15-Jan-19,BAGALKOT,110,BAGEWADI-MAMDAPUR2,"MAMDAPUR(B)_110,BABLESHWAR_1\r10",6:52,7:08,0:16,LINE FAULT
1,2,15-Jan-19,BAGALKOT,110,GHATAPRABHA220-GOKAK,GOKAK_110,5:00,5:16,0:16,LINE FAULT
2,3,15-Jan-19,BAGALKOT,110,GHATAPRABHA220-GOKAK,GOKAK_110,6:18,23:59,17:41,LINE FAULT
3,4,15-Jan-19,BAGALKOT,110,"110/33KV, HV4","LAKMANHALLI_110,ALNAVAR_33",13:12,13:19,0:07,TRANSFORMER FAULT
4,5,15-Jan-19,BAGALKOT,110,BPCL-NARGUND,NARGUND_110,21:00,23:51,2:51,LINE FAULT
...,...,...,...,...,...,...,...,...,...,...
669,670,21-Jan-19,TUMKUR,66,HANAGAL- AVADASOLAR_IPP_66,AVADASOLAR_IPP_66,12:42,12:47,0:04,LINE FAULT
670,671,21-Jan-19,TUMKUR,66,HONNALLI 220KV- SASUVEHALLI,SASUVEHALLI_66,14:07,14:20,0:12,LINE FAULT
671,672,21-Jan-19,TUMKUR,66,TR-1,LINGADAHALLI_TMK2_66,15:29,15:35,0:05,TRANSFORMER FAULT
672,673,21-Jan-19,TUMKUR,66,TR-1,MALEBENNUR_66,23:25,23:41,0:15,TRANSFORMER FAULT
673,674,21-Jan-19,TUMKUR,66,TR-1,NAGASAMUDRA_66,12:52,13:01,0:09,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2019\JAN 2019\22nd_to_28th_JAN_2019 .pdf

,0,1,2,3,4,5,6,7,8,9
0,1.0,22-Jan-19,BAGALKOT,110.0,BETAGERI- NAREGAL,NAREGAL_110,9:54,9:59,0:05,HAND TRIPPED
1,2.0,22-Jan-19,BAGALKOT,110.0,"220/110KV,LV-1&2",BELAGAUM_220,5:21,13:03,7:42,HAND TRIPPED
2,3.0,22-Jan-19,BAGALKOT,110.0,BELGAUM-HUKKERI(UCHAGOAN),UCHAGOAN_110,5:41,13:20,7:39,LOAD CURTAILMENT
3,4.0,22-Jan-19,BAGALKOT,110.0,CHIKKODI-SANKESHWAR,SANKESHWAR_110,6:30,6:57,0:27,LINE FAULT
4,5.0,22-Jan-19,BAGALKOT,220.0,CHIKKODI-KOLHAPUR1(TALANADAGE),CHIKKODI_220,6:57,20:23,13:26,LINE FAULT
...,...,...,...,...,...,...,...,...,...,...
903,904.0,28-Jan-19,TUMKUR,66.0,HARIYABBE-HIRIYUR,HARIYABBE_66,12:05,12:14,0:08,LINE FAULT
904,905.0,28-Jan-19,TUMKUR,66.0,KUKKAWADA- LINGADAHALLI,"TYAVANAGI_66,\rBASAVAPATNA_66,\rSANTEBENNUR_66",17:15,17:23,0:07,LINE FAULT
905,NaN,NaN,NaN,NaN,NaN,"SHYLAPURA_66,",NaN,NaN,NaN,NaN
906,906.0,NaN,NaN,NaN,NaN,"YNHOSKOTE_66,",NaN,NaN,NaN,NaN
907,NaN,28-Jan-19,TUMKUR,66.0,SHYLAPURA- MADHUGIRI,MANGALWADA_66,21:58,22:04,0:05,HAND TRIPPED

C:\C-STEP FOLDER\Transmission outage\2019\JULY 2019\02JULY2019_to_08_JULY_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,2-Jul-19,BAGALKOT,110,"110/11KV,HV3",BIJAPUR_110,20:44,21:04,0:20,HAND TRIPPED
1,2,2-Jul-19,BAGALKOT,110,"220/110KV,LV2",MK HUBLI_220,0:00,11:19,11:19,LINE CLEAR AVAILED
2,3,2-Jul-19,BAGALKOT,110,"110/11KV,HV2",YARAGATTI_110,15:04,15:51,0:47,LINE CLEAR AVAILED
3,4,2-Jul-19,BAGALKOT,110,JOG2-SIRSI,SIRSI_110,13:02,14:24,1:22,LINE CLEAR AVAILED
4,5,2-Jul-19,BAGALKOT,220,CHIKKODI-BELGAUM 2,CHIKKODI_220,2:50,6:55,4:05,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
630,631,08-Jul-19,TUMKUR,66,DODDASARANGI- ANTHRASANAHALLI,DODDASARANGI_66,15:07,15:32,0:25,LINE CLEAR AVAILED
631,632,08-Jul-19,TUMKUR,66,TR-2,GARAGA_66,15:24,16:06,0:42,LINE CLEAR AVAILED
632,633,08-Jul-19,TUMKUR,66,TR-1,HANAGAL_66,12:09,12:41,0:31,LINE CLEAR AVAILED
633,634,08-Jul-19,TUMKUR,66,TR-1,HARIHAR_66,8:36,9:22,0:45,TRANSFORMER FAULT
634,635,08-Jul-19,TUMKUR,66,HIRIYUR 220KV- ENERCON-1,ENERCON1_IPP_66,9:40,9:48,0:08,HAND TRIPPED

C:\C-STEP FOLDER\Transmission outage\2019\JULY 2019\09JULY2019_to_15_JULY_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,9-Jul-19,BAGALKOT,220,NAGJHARI-BIDNAL,BIDNAL_220,0:00,14:53,14:53,LINE CLEAR AVAILED
1,2,9-Jul-19,BAGALKOT,220,BELGAUM-CHIKKODI2,BELGAUM_220,0:00,7:39,7:39,LINE CLEAR AVAILED
2,3,9-Jul-19,BAGALKOT,220,BELGAUM-CHIKKODI2,BELGAUM_220,18:07,23:59,5:52,LINE CLEAR AVAILED
3,4,9-Jul-19,BAGALKOT,110,"110/11KV, HV2",AMBEWADI_220,4:50,5:42,0:52,TRANSFORMER FAULT
4,5,9-Jul-19,BAGALKOT,110,"110/33KV, HV3","ANKALI_110, NANDIKURALI_33",16:07,16:33,0:26,TRANSFORMER FAULT
...,...,...,...,...,...,...,...,...,...,...
692,693,15-Jul-19,TUMKUR,66,RANGANATHAPURA-WLSPNSOLAR2,WELSPUN_IPP_SOLAR_66 2,10:22,18:06,7:43,LINE FAULT
693,694,15-Jul-19,TUMKUR,66,THALLAK 220kV- SEI DIAMOND SOLAR_IPP_66,SEL DIAMOND SOLAR_IPP_66,18:47,22:34,3:47,LINE CLEAR AVAILED
694,695,15-Jul-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,8:55,16:58,8:03,LINE FAULT
695,696,15-Jul-19,TUMKUR,66,MADHUGIRI 220kV- SIRA 1,"GULIGENAHALLI_66,SIRA_66",13:02,13:04,0:01,LINE CLEAR AVAILED
696,697,15-Jul-19,TUMKUR,66,RANGENAHALLI -AZURESOLAR,AZURESOLAR_IPP_66,12:52,12:57,0:05,HAND TRIPPED

C:\C-STEP FOLDER\Transmission outage\2019\JULY 2019\16JULY2019_to_22_JULY_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,16-Jul-19,BAGALKOT,110,"110/33KV,HV1","CHIKKODI_110,KABBUR_33,VIJAYANAGAR_\r33",13:40,14:40,1:00,LINE CLEAR AVAILED
1,2,16-Jul-19,BAGALKOT,220,ALAMATTI1-BAGALKOT,BAGALKOT_220,13:45,20:26,6:41,LINE CLEAR AVAILED
2,3,16-Jul-19,BAGALKOT,110,"110/11KV,HV4",HUKKERI_110,15:27,15:39,0:12,LINE CLEAR AVAILED
3,4,16-Jul-19,BAGALKOT,220,VAJRAMATTI-MAHALINGAPUR1,VAJRAMATTI_220,9:39,17:45,8:06,NFBC ISSUED
4,5,16-Jul-19,BAGALKOT,220,VAJRAMATTI-MAHALINGAPUR2,VAJRAMATTI_220,17:52,18:21,0:29,NFBC ISSUED
...,...,...,...,...,...,...,...,...,...,...
612,613,22-Jul-19,HASSAN,400,TALAGU-NELAMANGALA#2,TALAGUPPA_400,21:30,23:59,2:29,LINE CLEAR AVAILED
613,614,22-Jul-19,HASSAN,220,SHRLKP-SGS,SHIRALKOPPA_220,11:20,15:48,4:28,LINE CLEAR AVAILED
614,615,22-Jul-19,HASSAN,66,BALLUPE-KANDLI,BALLUPETE_66,0:00,7:10,7:10,LINE FAULT
615,616,22-Jul-19,HASSAN,66,HV1,SIGEBAGI_66,10:35,10:40,0:05,LOAD CURTAILMENT
616,617,22-Jul-19,HASSAN,66,SIGEBAG-KDLGRE,SIGEBAGI_66,10:35,10:40,0:05,LOAD CURTAILMENT

C:\C-STEP FOLDER\Transmission outage\2019\JULY 2019\30JULY2019_to_05_AUG_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,30-Jul-19,BAGALKOT,110,"110/33KV,HV3","BAGEWADI_220,MUTTAGI_33,M\rANAGULI_33",7:00,18:45,11:45,TRANSFORMER FAULT
1,2,30-Jul-19,BAGALKOT,110,ATHANI220-AIGALI,AIGALI_110,0:00,0:17,0:17,LINE CLEAR AVAILED
2,3,30-Jul-19,BAGALKOT,110,ATHANI220-AIGALI,AIGALI_110,2:12,2:22,0:10,LINE FAULT
3,4,30-Jul-19,BAGALKOT,220,BELGAUM-CHIKKODI 2,BELGAUM_220,1:05,7:30,6:25,LINE CLEAR AVAILED
4,5,30-Jul-19,BAGALKOT,220,BELGAUM-CHIKKODI 2,BELGAUM_220,20:34,23:59,3:25,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
522,523,5-Aug-19,TUMKUR,66,TR-2,BADAVANAHALLI_66,20:23,20:30,0:07,TRANSFORMER FAULT
523,524,5-Aug-19,TUMKUR,66,HIRIYUR 220KV- ENERCON-1,ENERCON1_IPP_66,17:54,17:59,0:05,HAND TRIPPED
524,525,5-Aug-19,TUMKUR,66,HONNALLI 220KV- KUNDUR,"KUNDUR_66,MALEBENNUR_66",16:39,16:51,0:11,LINE FAULT
525,526,5-Aug-19,TUMKUR,66,TR-1,PULAMG_66,13:19,13:28,0:09,TRANSFORMER FAULT
526,527,5-Aug-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,10:37,12:40,2:02,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\JUN 2019\04JUNE2019_to_10_JUN_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,4-Jun-19,BAGALKOT,220,SHARAVATHY1-SIRSI,SIRSI_220,0:27,16:05,15:38,LINE FAULT
1,2,4-Jun-19,BAGALKOT,220,SHARAVATHY1-SIRSI,SIRSI_220,23:17,23:59,0:42,LINE FAULT
2,3,4-Jun-19,BAGALKOT,220,SHARAVATHY2-SIRSI,SIRSI_220,0:09,17:54,17:45,LINE FAULT
3,4,4-Jun-19,BAGALKOT,110,SIRSI-KUMTA1&2,SIRSI_110,0:00,12:20,12:20,LINE CLEAR AVAILED
4,5,4-Jun-19,BAGALKOT,110,SINDAGI-ALMEL,ALMEL_110,9:41,9:46,0:05,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
876,870,10-Jun-19,TUMKUR,66,HIRIYUR 220kV- BEVINAHALLI,"DASUDI_66, JAVAGONDANAHALLI_66,\rBEVINAHALLI_66",8:57,9:09,0:11,HAND TRIPPED
877,871,10-Jun-19,TUMKUR,66,HIRIYUR 220KV- RANGANATHPURA,RANGANATHAPURA_66,8:42,8:50,0:08,HAND TRIPPED
878,872,10-Jun-19,TUMKUR,66,HIRIYUR 220KV- RANGANATHPURA,RANGANATHAPURA_66,10:25,11:45,1:19,LINE CLEAR AVAILED
879,873,10-Jun-19,TUMKUR,66,MATHOD- AVNTI_SLR_IPP_66,AVNTI_SLR_IPP_66,8:50,9:59,1:09,LINE CLEAR AVAILED
880,874,10-Jun-19,TUMKUR,66,MATHOD- ENERCON1_IPP_66,ENERCON1_IPP_66,8:50,10:01,1:11,LINE CLEAR AVAILED

C:\C-STEP FOLDER\Transmission outage\2019\JUN 2019\11JUNE2019_to_17_JUN_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1.0,11-Jun-19,BAGALKOT,110.0,KUDACHI220-AINAPUR AINAPUR_110,5:37,5:40,0:03,LINE FAULT,None
1,2.0,11-Jun-19,BAGALKOT,110.0,AINAPUR-ATHANI SUGARS ATHANI_110,5:37,5:49,0:12,LINE FAULT,None
2,3.0,11-Jun-19,BAGALKOT,110.0,AINAPUR-ATHANI SUGARS ATHANI_110,12:05,13:26,1:21,LINE CLEAR AVAILED,None
3,4.0,11-Jun-19,BAGALKOT,110.0,"110/11KV,HV2 BHUTANAL_110",16:54,16:58,0:04,TRANSFORMER FAULT,None
4,5.0,11-Jun-19,BAGALKOT,110.0,RAIBAG-ITANAL ITANAL_110,19:06,19:18,0:12,LINE FAULT,None
...,...,...,...,...,...,...,...,...,...,...
756,748.0,17-Jun-19,MYSORE,66.0,VAJAMANGALA-KADAKOLA 1,"AYRALLI_66, MARADIHUNDI_66",5:41,5:55,0:14,LINE FAULT
757,749.0,17-Jun-19,TUMKUR,110.0,TR-1,KEREKODI_110,9:38,10:12,0:33,LINE CLEAR AVAILED
758,750.0,17-Jun-19,TUMKUR,66.0,TR-2,CHANNAGIRI_66,11:09,11:11,0:01,TRANSFORMER FAULT
759,751.0,17-Jun-19,TUMKUR,66.0,HIRIYUR 220KV- ENERCON-1,ENERCON1_IPP_66,9:50,9:56,0:06,HAND TRIPPED
760,752.0,17-Jun-19,TUMKUR,66.0,TR-2,MALEBENNUR_66,11:08,11:15,0:06,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2019\JUN 2019\18JUNE2019_to_24_JUN_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,18-Jun-19,BAGALKOT,110,"110/33KV,HV2","ANKOLA_110,MASTIGATTA_33,SEABIRD_11\r0",11:06,11:36,0:30,LINE CLEAR AVAILED
1,2,18-Jun-19,BAGALKOT,110,ATHANI220-BALIGERI(TAUSHI),BALIGERI(TAUSHI)_110,5:43,6:13,0:30,LINE FAULT
2,3,18-Jun-19,BAGALKOT,110,"110/11KV,HV2",BIDNAL_110,10:23,16:33,6:10,LINE CLEAR AVAILED
3,4,18-Jun-19,BAGALKOT,110,CHIKKODI220-SANKESHWARA,SANKESHWARA_110,9:36,10:25,0:49,LINE CLEAR AVAILED
4,5,18-Jun-19,BAGALKOT,110,CHIKKODI220-ANKALI,ANKALI_110,11:41,12:28,0:47,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
674,675,24-Jun-19,TUMKUR,66,CHIKKABANAGERE- GLOBAL TECKPARK,GLOBAL TECKPARK_IPP_66,12:59,13:25,0:25,HAND TRIPPED
675,676,24-Jun-19,TUMKUR,66,CHITRADURGA 220kV- PANDARAHALLI 2,"HIREGUNTANUR_66, SIRIGERE_66,\rBRAHMASAGARA_IP...",17:12,17:52,0:39,LINE FAULT
676,677,24-Jun-19,TUMKUR,66,TR-1,DEVARAHALLI_66,12:25,12:43,0:18,TRANSFORMER FAULT
677,678,24-Jun-19,TUMKUR,66,KUKKAWADA-\rLINGADAHALLI(CHANNAGIRI),"KUKKAWADA_66, TYAVANAGI_66,\rBASAVAPATNA_66, S...",4:53,5:13,0:19,LINE FAULT
678,679,24-Jun-19,TUMKUR,66,CHITRADURGA 66kV- PANDARAHALLI 2,"PANDARAHALLI_66,CHITRADURGA_220",16:58,17:53,0:55,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\JUN 2019\25JUNE2019_to_01_JULY_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,25-Jun-19,BAGALKOT,220,NAGJHARI1-AMBEWADI,AMBEWADI_220,12:03,12:29,0:26,LINE FAULT
1,2,25-Jun-19,BAGALKOT,110,"110/11KV,HV2",AMBEWADI_220,15:08,17:42,2:34,TRANSFORMER FAULT
2,3,25-Jun-19,BAGALKOT,110,BETAGERI-NAREGALL,NAREGALL_110,5:56,6:12,0:16,LINE FAULT
3,4,25-Jun-19,BAGALKOT,110,"110/11KV,HV4",BELGAUM_110,15:17,16:44,1:27,LINE CLEAR AVAILED
4,5,25-Jun-19,BAGALKOT,110,RON 1-GAJENDRAGAD,GAJENDRAGAD_110,5:30,13:17,7:47,MAIN SUPPLY FAILURE
...,...,...,...,...,...,...,...,...,...,...
747,748,01-Jul-19,TUMKUR,66,CHITRADURGA 220kV- PANDARAHALLI 1,"HIREGUNTANUR_66, SIRIGERE_66,\rBRAHMASAGARA_IP...",14:40,16:00,1:19,LINE CLEAR AVAILED
748,749,01-Jul-19,TUMKUR,66,CHITRADURGA 220kV- SUZLON 1,"SUZLON1_IPP_66,",14:46,17:00,2:13,LINE CLEAR AVAILED
749,750,01-Jul-19,TUMKUR,66,CHITRADURGA 220kV- SUZLON2,"SUZLON1_IPP_66, 66",14:48,16:44,1:56,LINE CLEAR AVAILED
750,751,01-Jul-19,TUMKUR,66,CHITRADURGA 220kV- TURUVANUR,"MADANAYAKANAHALLI_66,\rTURUVANUR_66, BIDARKERE...",14:40,15:21,0:40,HAND TRIPPED
751,752,01-Jul-19,TUMKUR,66,TR-2,HULIYURDURGA_66,14:17,14:25,0:07,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2019\JUN 2019\28MAY2019_to_03_JUN_2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,28-May-19,BAGALKOT,66,"66/11KV,HV 2",HARIHAR-HOSPET_66,17:50,17:56,0:06,HAND TRIPPED
1,2,28-May-19,BAGALKOT,110,ATHANI-AIGALI,AIGALI_110,5:34,5:52,0:18,LINE FAULT
2,3,28-May-19,BAGALKOT,110,"110/11KV,HV 2",BIJAPUR_110,6:49,8:29,1:40,TRANSFORMER FAULT
3,4,28-May-19,BAGALKOT,110,SAIDAPUR-DAVALESHWAR,DAVALESHWAR_110,5:39,7:15,1:36,LINE FAULT
4,5,28-May-19,BAGALKOT,110,"110/11KV,HV 2",KALAGHATGI_110,17:16,17:23,0:07,TRANSFORMER FAULT
...,...,...,...,...,...,...,...,...,...,...
1062,1063,3-Jun-19,TUMKUR,66,TR-1,NYAMATHI_66,17:47,18:01,0:14,TRANSFORMER FAULT
1063,1064,3-Jun-19,TUMKUR,66,TR-1,SAVALANGA_66,1:34,7:55,6:21,MAIN SUPPLY FAILURE
1064,1065,3-Jun-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,7:45,8:30,0:45,LINE FAULT
1065,1066,3-Jun-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,9:32,14:32,5:00,LINE FAULT
1066,1067,3-Jun-19,TUMKUR,66,TR-2,THIMMASANDRA_66,8:41,10:01,1:20,TRANSFORMER FAULT

C:\C-STEP FOLDER\Transmission outage\2019\MAR 2019\05MAR2019to11MAR2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,5-Mar-19,BAGALKOT,110,"110/11KV,HV-1",ANANDNAGAR_110,7:42,7:52,0:10,TRANSFORMER FAULT
1,2,5-Mar-19,BAGALKOT,110,"110/11KV,HV-2",BAGALKOT_110,10:31,11:55,1:24,TRANSFORMER FAULT
2,3,5-Mar-19,BAGALKOT,110,"110/11KV,HV-2",BAGALKOT_110,13:04,13:52,0:48,TRANSFORMER FAULT
3,4,5-Mar-19,BAGALKOT,110,"110/11KV,HV-1",BILAGI_110,12:29,14:09,1:40,LINE CLEAR AVAILED
4,5,5-Mar-19,BAGALKOT,110,CHIKKODI-SANKESHWAR,SANKESHWAR_110,6:04,6:09,0:05,LINE FAULT
...,...,...,...,...,...,...,...,...,...,...
847,848,11-Mar-19,TUMKUR,66,MADANAYAKANAHALLI-\rCHITRADURGA220,MADANAYAKANAHALLI_66,18:40,18:51,0:10,LINE FAULT
848,849,11-Mar-19,TUMKUR,66,NEELAGUNDA 220kV-HULUVAGALU,HALUVAGALU_66,6:17,6:28,0:10,LINE FAULT
849,850,11-Mar-19,TUMKUR,66,PANDARAHALLI- HOLALKERE,PANDARAHALLI_66,4:05,4:39,0:33,LINE FAULT
850,851,11-Mar-19,TUMKUR,66,PANDARAHALLI- HOLALKERE,PANDARAHALLI_66,16:15,16:41,0:25,LINE FAULT
851,852,11-Mar-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,10:19,11:48,1:29,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\MAR 2019\12MAR2019to18MAR2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,12-Mar-19,BAGALKOT,220,AMBEWADI-PONDA 2,AMBEWADI_220,0:00,16:28,16:28,LINE CLEAR AVAILED
1,2,12-Mar-19,BAGALKOT,220,AMBEWADI-NARENDRA 1,AMBEWADI_220,11:49,12:31,0:42,HAND TRIPPED
2,3,12-Mar-19,BAGALKOT,220,AMBEWADI-NAGJARI 1,AMBEWADI_220,11:50,12:31,0:41,HAND TRIPPED
3,4,12-Mar-19,BAGALKOT,110,"110/33KV,HV3","BAGALKOT_220,KATAGERI_33",10:55,13:38,2:43,LINE CLEAR AVAILED
4,5,12-Mar-19,BAGALKOT,110,"110/11KV,HV2",BANAHATTI_110,17:06,17:49,0:43,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
1021,1022,18-Mar-19,TUMKUR,66,TR-1,KATTIGE_66,6:30,11:02,4:32,LINE CLEAR AVAILED
1022,1023,18-Mar-19,TUMKUR,66,TR-1,KATTIGE_66,16:06,18:44,2:38,LINE CLEAR AVAILED
1023,1024,18-Mar-19,TUMKUR,66,MATHOD- PANCHANAHALLI,"PANCHANAHALLI_66, GARAGA_66",6:23,6:38,0:15,MAIN SUPPLY FAILURE
1024,1025,18-Mar-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,9:50,14:14,4:24,LINE FAULT
1025,1026,18-Mar-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR2,WELSPUNSOLAR1_IPP_66,15:01,15:38,0:37,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\MAR 2019\19MAR2019to25MAR2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,19-Mar-19,BAGALKOT,110,AMBEWADI-NK2,KAVALAWAD_110,9:56,12:48,2:52,LINE CLEAR AVAILED
1,2,19-Mar-19,BAGALKOT,110,AMBEWADI-NK1,HALIYAL_110,0:00,15:50,15:50,LINE CLEAR AVAILED
2,3,19-Mar-19,BAGALKOT,110,AMBEWADI-NK1,HALIYAL_110,15:39,15:42,0:03,LINE FAULT
3,4,19-Mar-19,BAGALKOT,110,AMBEWADI-NK1,HALIYAL_110,15:49,18:16,2:27,LINE FAULT
4,5,19-Mar-19,BAGALKOT,110,AMBEWADI-NK1,HALIYAL_110,18:25,18:30,0:05,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
581,582,25-Mar-19,TUMKUR,66,KUKKAWADA-\rLINGADAHALLI(CHANNAGIRI),"TYAVANAGI_66, BASAVAPATNA_66,\rSANTEBENNUR_66",9:04,9:16,0:11,LINE FAULT
582,583,25-Mar-19,TUMKUR,66,TR-2,NAGALMADIKE_66,11:35,12:41,1:05,TRANSFORMER FAULT
583,584,25-Mar-19,TUMKUR,66,NAGASAMUDRA- IPP_SOLAR,WELSPUN_IPP_SOLAR_66,12:30,13:00,0:30,HAND TRIPPED
584,585,25-Mar-19,TUMKUR,66,NAGASAMUDRA- RAMPUR,"NAGASAMUDRA_66, RAMPURA_66",12:30,12:59,0:29,HAND TRIPPED
585,586,25-Mar-19,TUMKUR,66,NAYAKANAHATTI66-HIREMALLANHOLE,HIREMALLANAHOLE_66,15:33,15:34,0:01,MAIN SUPPLY FAILURE

C:\C-STEP FOLDER\Transmission outage\2019\MAR 2019\26MAR2019to01APR2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,26-Mar-19,BAGALKOT,220,NAGJHARI 1-AMBEWADI,AMBEWADI_220,13:22,23:59,10:37,LINE FAULT
1,2,26-Mar-19,BAGALKOT,220,AMBEWADI-NARENDRA 2,AMBEWADI_220,0:00,13:25,13:25,LINE CLEAR AVAILED
2,3,26-Mar-19,BAGALKOT,110,"110/11KV,HV2",AMBEWADI_220,11:24,11:48,0:24,HAND TRIPPED
3,4,26-Mar-19,BAGALKOT,110,ATHANI SUGARS-AINAPUR,AINAPUR_110,13:29,16:49,3:20,LINE CLEAR AVAILED
4,5,26-Mar-19,BAGALKOT,220,HIREBENDIGERI 2-BIDNAL,BIDNAL_220,0:00,16:20,16:20,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
1074,1075,1-Apr-19,TUMKUR,66,HONNALLI 220KV- SASUVEHALLI,SASUVEHALLI_66,14:24,15:22,0:58,LINE FAULT
1075,1076,1-Apr-19,TUMKUR,66,JAVAGONDANAHALLI- BEVINAHALLI,JAVAGONDANAHALLI_66,23:24,23:25,0:01,LINE CLEAR AVAILED
1076,1077,1-Apr-19,TUMKUR,66,JAVAGONDANAHALLI- SIRA,JAVAGONDANAHALLI_66,23:24,23:25,0:01,LINE CLEAR AVAILED
1077,1078,1-Apr-19,TUMKUR,66,KUKKAWADA- LINGADAHALLI(CHANNAGIRI),"TYAVANAGI_66, BASAVAPATNA_66,\rSANTEBENNUR_66",9:43,9:45,0:01,MAIN SUPPLY FAILURE
1078,1079,1-Apr-19,TUMKUR,66,THALLAK 220kV- CHALLAKERE-2,"CHALLAKERE_66, SANIKERE_66",6:01,6:09,0:07,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\MAY 2019\07MAY2019to13MAY2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1,7-May-19,BAGALKOT,220,BIDNAL-SOUNDATTI,BIDNAL_220,16:38,23:04,6:26,LINE FAULT
1,2,7-May-19,BAGALKOT,220,CHIKKODI-MUDASHINGI (KOLHAPUR 2),CHIKKODI_220,10:57,15:10,4:13,LINE CLEAR AVAILED
2,3,7-May-19,BAGALKOT,400,400/1220KV ICT2(HV&LV),DHONI_400,6:22,7:28,1:06,TRANSFORMER FAULT
3,4,7-May-19,BAGALKOT,400,400/220KV GUDADALLI (TIE BREAKER2),DHONI_400,6:22,7:52,1:30,LINE FAULT
4,5,7-May-19,BAGALKOT,110,"110/11KV,HV1",NAVANAGAR(H)_110,9:11,16:09,6:58,LINE CLEAR AVAILED
...,...,...,...,...,...,...,...,...,...,...
739,740,13-May-19,TUMKUR,66,MADHUGIRI 220kV- PULAMAGATTA,PULAMG_66,19:08,19:12,0:03,HAND TRIPPED
740,741,13-May-19,TUMKUR,66,MADHUGIRI 220kV- RANGANATHAPURA,"SIRA_66, KALLAMBELLA_66,\rBUKKAPATNA_66",19:08,19:10,0:02,HAND TRIPPED
741,742,13-May-19,TUMKUR,66,TR-2,TAVAREKERE(C)_66,11:20,12:29,1:09,TRANSFORMER FAULT
742,743,13-May-19,TUMKUR,66,THALLAK 220kV- WELSPUN SOLAR1,WELSPUNSOLAR1_IPP_66,9:37,11:42,2:04,LINE FAULT
743,744,13-May-19,TUMKUR,66,TR-1,TUMKUR_66,11:10,11:18,0:07,HAND TRIPPED

C:\C-STEP FOLDER\Transmission outage\2019\MAY 2019\14MAY2019to20MAY2019.pdf

,0,1,2,3,4,5,6,7,8,9
0,1.0,14-May-19,BAGALKOT,110.0,"110/11KV, HV2",BANAHATTI_110,10:15,13:39,3:24,LINE CLEAR AVAILED
1,2.0,14-May-19,BAGALKOT,220.0,ATRIA1-BAGEWADI,BAGEWADI_220,14:10,15:08,0:58,LINE FAULT
2,3.0,14-May-19,BAGALKOT,220.0,FORTUNEFIVE1&2-BAGEWADI,BAGEWADI_220,14:10,15:09,0:59,LINE CLEAR AVAILED
3,4.0,14-May-19,BAGALKOT,220.0,RBRK-BAGEWADI,BAGEWADI_220,14:10,15:24,1:14,LINE CLEAR AVAILED
4,5.0,14-May-19,BAGALKOT,220.0,ALAMATTI2-BAGEWADI,BAGEWADI_220,15:53,16:11,0:18,HAND TRIPPED
...,...,...,...,...,...,...,...,...,...,...
1005,982.0,20-May-19,TUMKUR,66.0,CHIKKABANAGERE- GLOBAL\rTECKPARK,GLOBAL TECKPARK_IPP_66,8:48,9:29,0:41,HAND TRIPPED
1006,983.0,20-May-19,TUMKUR,66.0,LINGADHALLI-CHANNAGIRI,"CHANNAGIRI_66,DEVARAHALLI_66\r,BENKIKERE_66,GO...",13:51,18:31,4:40,MAIN SUPPLY FAILURE
1007,984.0,20-May-19,TUMKUR,66.0,TR-1,LINGADAHALLY_66,7:37,8:41,1:04,TRANSFORMER FAULT
1008,985.0,20-May-19,TUMKUR,66.0,LINGADAHALLI- SHIMOGA,LINGDHALLI_66,7:02,15:33,8:31,LINE FAULT
1009,986.0,20-May-19,TUMKUR,66.0,LINGADAHALLI- SHIMOGA,LINGDHALLI_66,18:31,22:23,3:52,LINE FAULT

C:\C-STEP FOLDER\Transmission outage\2019\MAY 2019\21MAY2019_to_27MAY2019 (1).pdf

KeyboardInterrupt:

In [153]:
x_files = [os.path.join(root, name)
             for root, dirs, files in os.walk(os.getcwd())
             for name in files
             if name.endswith((r".xlsx"))]

In [154]:
x_files

['C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2018\\DECEMBER-2018.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2018\\SEPTEMBER-2018.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2018\\~$DECEMBER-2018.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2019\\AUGUST-2019.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2019\\DECEMBER-2019.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2019\\FEBRUARY-2019.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2019\\JULY-12019.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2019\\JUNE-12019.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2019\\MAY-2019.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2019\\NOVEMBER-2019.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2019\\SEPTEMBER-2019.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\APRIL-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\AUGUST-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\DECEMBER-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\FEBRUARY-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\JULY-20.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\JUNE-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\MARCH-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\MAY-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\NOVEMBER-20.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\OCTOBER-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2020\\SEPTEMBER-2020.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\APRIL-2021.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\Final max n min vtg-December- 21.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\JANUARY-2021.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\JULY-2021.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\JUNE-2021.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\MARCH-2021.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\MAY-21.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\Nov-21.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\October-2021.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2022\\MAX_MIN_APR_2022.xlsx',
 'C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\max&min voltage\\MAX&MIN BUS VTG.xlsx',
 'C:\\C-STEP FOLDER\\Transmission outage\\2019\\APR 2019\\02APR2019to08APR2019.xlsx',
 'C:\\C-STEP FOLDER\\Transmission outage\\2019\\APR 2019\\09APR2019to15APR2019.xlsx',
 'C:\\C-STEP FOLDER\\Transmission outage\\2019\\APR 2019\\23APR2019to29APR2019.xlsx',
 'C:\\C-STEP FOLDER\\Transmission outage\\2019\\APR 2019\\30APR2019to06MAY2019.xlsx']

In [155]:
pd.read_excel(x_files[0])

XLRDError: Can't find workbook in OLE2 compound document

In [139]:
import glob
gfile = glob.glob(x_files[0])
df = pd.concat(pd.read_excel(x_files[0]))

XLRDError: Can't find workbook in OLE2 compound document

In [131]:
import openpyxl
def data_excel(file, header):
    df = pd.read_excel(file, header=[header], engine='openpyxl')
    return df

In [132]:
display(data_excel(x_files[0], 2))

BadZipFile: File is not a zip file

In [97]:
!pip install xlwings

Collecting xlwings
  Downloading xlwings-0.27.13-py3-none-any.whl (1.0 MB)
     ---------------------------------------- 1.0/1.0 MB 5.5 MB/s eta 0:00:00
Requirement already satisfied: pywin32>=224 in c:\python310\lib\site-packages (from xlwings) (304)
Installing collected packages: xlwings

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Python310\\xlwings32-0.27.13.dll'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)

In [102]:
import openpyxl
import xlwings as xw

In [127]:
ws = xw.Book(x_files[0]).sheets['GULBARGA']
v1 = ws.range("A1:A10").value
# v2 = ws.range("F6").value
print("Result:", v1)
# dataframe = openpyxl.load_workbook('C:\\C-STEP FOLDER\\MAX&MIN VOLTAGE\\2021\\October-2021.xlsx')

Result: ['KARNATAKA POWER TRANSMISSION CORPORATION LIMITED', 'MAXIMUM AND MINIMUM VOLTAGE OF STATION BUS  RECORDED DURING DECEMBER-2018 IN TRANSMISSION ZONE,GULBARGA', None, 'SL NO', None, 1.0, 2.0, 3.0, 4.0, 5.0]

In [150]:
x_files = [os.path.join(root, name)
             for root, dirs, files in os.walk(os.getcwd())
             for name in files
             if name.endswith((r".xlsx"))]

In [151]:
def data_excel(file, header):
    df = pd.read_excel(file, header=[header])
    return df

In [152]:
for f in x_files:
    print(f)
    display(data_excel(f,2))

C:\C-STEP FOLDER\MAX&MIN VOLTAGE\2018\DECEMBER-2018.xlsx

XLRDError: Can't find workbook in OLE2 compound document